#!/usr/bin/env python3
"""parse_flight_log.py -- the CONSUMER for `flight/deploy/real_flight.py --log-csv`.

WHY THIS EXISTS (audit 2026-07-25, completeness critic: "instrument gap the map
missed"). `real_flight.py` writes a 36-column per-tick decision log -- the ONLY
onboard record of WHY the interceptor did what it did: every state transition,
every failsafe reason, and the guidance state behind each ENGAGE setpoint. Before
this file, NOTHING read it. `git grep -l log_csv` returned one hit
(scripts/check_real_flight_sitl.sh) which passes the path and never parses it,
and `tests/contract_helpers.py` pinned only the SIM CSV's header. So the record a
first real flight produces had no scorer, no schema pin, and nothing asserting it
was even non-empty -- while `scripts/field_score.py` scores the FC's .BIN/ULog,
a different file entirely.

WHAT IT REPORTS
  1. STATE MACHINE -- every transition (t, from -> to), time in each state, the
     terminal state, and whether the flight TERMINATED in SAFE.
  2. FAILSAFES -- every distinct `safe_reason` with its first tick. This column is
     the failsafe vocabulary: mission_timeout, link_denied:*, standby_timeout,
     arm_gate_failed_at_go, dash_timeout_no_acquire, dash_distance_bound,
     breakoff_complete.
  3. ENGAGE STATS -- ticks, detected ticks, sp_source histogram (guided / coast /
     hold / <state>), r_hat span, |lambda_dot| percentiles, and the health flags
     (stale, track_broken, own_state_ok=0, terminal_coast).
  4. ZERO-COMMAND TICKS -- see below.

THE ZERO-COMMAND CHECK MIRRORS THE SIM AUDITOR, deliberately and by the same
numbers: `scripts/audit_per_tick.py` check (e) (ZERO_CMD_TOL 1e-6,
ZERO_CMD_FAIL_FRAC 0.5, ZERO_CMD_MIN_N 10). That check exists because
`scripts/m4_intercept.py`'s terminal freeze latched an unset (0.0, 0.0) whenever
ENGAGE began inside the freeze range, so the whole ENGAGE phase commanded ZERO
horizontal velocity -- braking, not steering -- on 29/44 engaged flights across
five arms, while the audit printed PASS. The hardware executor runs the same
mechanization, so the same defect can fly. Same tolerance, same fail fraction,
same minimum population, so a sim finding and a field finding are comparable
numbers rather than two similar-sounding ones. This tool imports those constants
from audit_per_tick when it can, and pins them if not.

ERROR POLICY (docs/error_handling_policy.md -- this file is an INSTRUMENT):
  * NO VACUOUS VERDICTS. A log with zero rows, or a zero-tick ENGAGE population,
    is UNCERTAIN and exits non-zero -- never a PASS. A shrinking denominator is
    COUNTED and printed, never absorbed.
  * FAIL CLOSED on measured quantities: a column that should carry a number and
    does not is reported as missing; nothing is defaulted in.
  * The header is validated against the PRODUCER's own `_CSV_FIELDS` when
    real_flight is importable (see tests/test_parse_flight_log_contract.py, whose
    fixture is generated by CALLING real_flight's writer).

EXIT CODES
  0  OK       -- parsed, and every gated check passed
  1  FAIL     -- a gated check failed (zero-command, or no ENGAGE with --require-engage)
  2  USAGE    -- bad arguments / unreadable file
  3  UNCERTAIN-- parsed but a verdict could not be computed on a real population
                 (empty log, no ENGAGE ticks); never reported as a pass

USAGE
    scripts/field/parse_flight_log.py logs/real_flight_20260801T....csv
    scripts/field/parse_flight_log.py LOG.csv --json summary.json --require-engage
    scripts/field/parse_flight_log.py --self-test
"""
from __future__ import annotations

import argparse
import csv
import json
import os
import sys
from collections import Counter, OrderedDict

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

EXIT_OK, EXIT_FAIL, EXIT_USAGE, EXIT_UNCERTAIN = 0, 1, 2, 3

# --- the zero-command gate, mirrored from scripts/audit_per_tick.py check (e) --
# Imported when possible so the two cannot drift; the literals are the pin.
ZERO_CMD_TOL = 1e-6
ZERO_CMD_FAIL_FRAC = 0.5
ZERO_CMD_MIN_N = 10


def _sync_zero_cmd_constants():
    """Adopt audit_per_tick's constants if that module imports (it is stdlib-only
    but lives under scripts/). Returns the provenance string for the report."""
    global ZERO_CMD_TOL, ZERO_CMD_FAIL_FRAC, ZERO_CMD_MIN_N
    try:
        sys.path.insert(0, os.path.join(REPO_ROOT, "scripts"))
        import audit_per_tick as apt  # noqa: WPS433
        ZERO_CMD_TOL = apt.ZERO_CMD_TOL
        ZERO_CMD_FAIL_FRAC = apt.ZERO_CMD_FAIL_FRAC
        ZERO_CMD_MIN_N = apt.ZERO_CMD_MIN_N
        return "scripts/audit_per_tick.py (imported)"
    except Exception:  # noqa: BLE001 -- a field Pi may not carry the sim tree
        return "pinned literals (audit_per_tick.py not importable here)"


def producer_fields():
    """The PRODUCER's own column tuple, for header validation. Returns None when
    real_flight is not importable (e.g. on a bare Pi without mavsdk)."""
    try:
        sys.path.insert(0, REPO_ROOT)
        from flight.deploy.real_flight import _CSV_FIELDS  # noqa: WPS433
        return list(_CSV_FIELDS)
    except Exception:  # noqa: BLE001
        return None


# ============================================================ parsing


class ParseError(RuntimeError):
    pass


def load_rows(path):
    if not os.path.isfile(path):
        raise ParseError(f"no such flight log: {path}")
    with open(path, newline="") as f:
        reader = csv.DictReader(f)
        header = reader.fieldnames
        rows = list(reader)
    if not header:
        raise ParseError(f"{path} has no header line -- not a flight log")
    return header, rows


def _f(row, key):
    """Float or None. An empty cell is None (the producer writes '' for
    not-applicable), NOT a defaulted zero."""
    v = row.get(key)
    if v is None or v == "":
        return None
    try:
        return float(v)
    except ValueError:
        return None


def _b(row, key):
    v = row.get(key)
    if v in (None, ""):
        return None
    return v not in ("0", "False", "false")


def summarize(header, rows):
    """Build the summary dict. Pure: no printing, no exits -- so the tests can
    assert on it directly."""
    s = {
        "n_ticks": len(rows),
        "columns": list(header),
        "header_matches_producer": None,
        "missing_columns": [],
        "extra_columns": [],
        "t_start": None, "t_end": None, "duration_s": None,
        "transitions": [],
        "state_ticks": {},
        "terminal_state": None,
        "terminated_in_safe": False,
        "safe_reasons": [],
        "states_visited": [],
        "engage": {},
        "zero_cmd": {},
        "notes": [],
    }

    fields = producer_fields()
    if fields is not None:
        s["header_matches_producer"] = (list(header) == fields)
        s["missing_columns"] = [c for c in fields if c not in header]
        s["extra_columns"] = [c for c in header if c not in fields]
    else:
        s["notes"].append(
            "flight.deploy.real_flight not importable -- header NOT validated "
            "against the producer (schema drift would go unseen here)")

    # EMPTY LOG: note it and KEEP GOING. There used to be a `return s` here, which
    # left `engage`/`zero_cmd` as bare {} -- and report() indexes
    # s['zero_cmd']['population'], so the documented exit-3 UNCERTAIN path died
    # with a KeyError traceback and exit 1 ("a gated check FAILED", i.e. "the
    # terminal did not actuate") on a flight that simply produced no ticks, and
    # the --json record was never written (2026-07-26). Every block below already
    # degrades correctly on rows == [] (empty counters, frac None), so the fix is
    # to let them run rather than to sprinkle .get() guards in the consumers.
    if not rows:
        s["notes"].append("EMPTY LOG: header only, zero ticks")

    ts = [_f(r, "t_s") for r in rows]
    ts = [t for t in ts if t is not None]
    if ts:
        s["t_start"], s["t_end"] = ts[0], ts[-1]
        s["duration_s"] = ts[-1] - ts[0]

    # --- (1) state machine -------------------------------------------------
    ticks = Counter()
    prev = None
    visited = []
    for r in rows:
        st = r.get("state") or ""
        ticks[st] += 1
        if st != prev:
            s["transitions"].append({
                "t_s": _f(r, "t_s"), "from": prev, "to": st,
                "streak": r.get("streak"), "alt_m": _f(r, "alt_m"),
            })
            visited.append(st)
            prev = st
    s["state_ticks"] = dict(ticks)
    s["states_visited"] = visited
    s["terminal_state"] = prev
    s["terminated_in_safe"] = (prev == "SAFE")

    # --- (2) failsafes -----------------------------------------------------
    seen = OrderedDict()
    for r in rows:
        why = (r.get("safe_reason") or "").strip()
        if why and why not in seen:
            seen[why] = {"reason": why, "first_t_s": _f(r, "t_s"),
                         "state": r.get("state")}
    s["safe_reasons"] = list(seen.values())

    # --- (3)+(4) ENGAGE ----------------------------------------------------
    eng = [r for r in rows if (r.get("state") or "") == "ENGAGE"]
    n_det = sum(1 for r in eng if _b(r, "det_new"))
    src = Counter((r.get("sp_source") or "") for r in eng)
    r_hats = [v for v in (_f(r, "r_hat_m") for r in eng) if v is not None]
    lam_dots = sorted(abs(v) for v in
                      (_f(r, "lambda_dot_deg_s") for r in eng) if v is not None)

    def pct(xs, q):
        if not xs:
            return None
        i = min(len(xs) - 1, max(0, int(round(q * (len(xs) - 1)))))
        return xs[i]

    s["engage"] = {
        "n_ticks": len(eng),
        "n_detected_ticks": n_det,
        "sp_source": dict(src),
        "r_hat_min_m": min(r_hats) if r_hats else None,
        "r_hat_max_m": max(r_hats) if r_hats else None,
        "n_r_hat_present": len(r_hats),
        "abs_lambda_dot_p50": pct(lam_dots, 0.5),
        "abs_lambda_dot_p95": pct(lam_dots, 0.95),
        "n_terminal_coast": sum(1 for r in eng if _b(r, "terminal_coast")),
        "n_stale": sum(1 for r in eng if _b(r, "stale")),
        "n_track_broken": sum(1 for r in eng if _b(r, "track_broken")),
        "n_own_state_bad": sum(1 for r in eng if _b(r, "own_state_ok") is False),
        "health_flags": dict(Counter(
            flag for r in eng for flag in (r.get("health") or "").split("|") if flag)),
    }

    # ZERO-COMMAND: mirrors audit_per_tick check (e). Population = ENGAGE ticks
    # CARRYING A DETECTION (the ticks that had something to steer on). Ticks with
    # an unparseable command are counted separately, never silently dropped.
    n_pop = n_zero = n_unparseable = 0
    for r in eng:
        if not _b(r, "det_new"):
            continue
        vn, ve = _f(r, "v_north"), _f(r, "v_east")
        if vn is None or ve is None:
            n_unparseable += 1
            continue
        n_pop += 1
        if abs(vn) < ZERO_CMD_TOL and abs(ve) < ZERO_CMD_TOL:
            n_zero += 1
    s["zero_cmd"] = {
        "population": n_pop,
        "n_zero": n_zero,
        "n_unparseable_command": n_unparseable,
        "frac": (n_zero / n_pop) if n_pop else None,
        "tol": ZERO_CMD_TOL,
        "fail_frac": ZERO_CMD_FAIL_FRAC,
        "min_n": ZERO_CMD_MIN_N,
    }
    return s


_SEVERITY = {EXIT_OK: 0, EXIT_UNCERTAIN: 1, EXIT_FAIL: 2}


def worse(a, b):
    """Combine two exit codes by SEVERITY, not by numeric value -- UNCERTAIN is
    3 and FAIL is 1, so a naive max() would let an UNCERTAIN mask a FAIL."""
    return a if _SEVERITY[a] >= _SEVERITY[b] else b


def verdicts(s, require_engage=False):
    """Return (exit_code, [ (level, text), ... ]). Gated checks only."""
    out = []
    code = EXIT_OK

    if s["n_ticks"] == 0:
        return EXIT_UNCERTAIN, [("UNCERTAIN",
                                 "the log has ZERO ticks -- nothing to verdict "
                                 "on (a verdict computed on zero units is never "
                                 "a PASS)")]

    if s["header_matches_producer"] is False:
        code = worse(code, EXIT_FAIL)
        out.append(("FAIL",
                    f"header DRIFTED from flight/deploy/real_flight._CSV_FIELDS: "
                    f"missing={s['missing_columns']} extra={s['extra_columns']}"))
    elif s["header_matches_producer"] is True:
        out.append(("OK", "header matches the producer's _CSV_FIELDS exactly"))

    e = s["engage"]
    z = s["zero_cmd"]
    if e.get("n_ticks", 0) == 0:
        lvl = "FAIL" if require_engage else "UNCERTAIN"
        out.append((lvl, "ZERO ENGAGE ticks -- the terminal never ran, so no "
                         "terminal verdict exists for this flight"))
        code = worse(code, EXIT_FAIL if require_engage else EXIT_UNCERTAIN)
    elif z["population"] == 0:
        out.append(("UNCERTAIN",
                    f"{e['n_ticks']} ENGAGE ticks but ZERO carried a detection "
                    f"with a parseable command "
                    f"({z['n_unparseable_command']} unparseable) -- the "
                    f"zero-command gate has no population to score"))
        code = worse(code, EXIT_UNCERTAIN)
    elif z["population"] < ZERO_CMD_MIN_N:
        out.append(("UNCERTAIN",
                    f"zero-command gate UNDERPOWERED: population {z['population']} "
                    f"< {ZERO_CMD_MIN_N} (n_zero={z['n_zero']}, "
                    f"frac={z['frac']:.2f}) -- reported, not gated"))
        code = worse(code, EXIT_UNCERTAIN)
    elif z["frac"] > ZERO_CMD_FAIL_FRAC:
        code = worse(code, EXIT_FAIL)
        out.append(("FAIL",
                    f"THE TERMINAL DID NOT ACTUATE: {z['n_zero']}/{z['population']} "
                    f"({z['frac']:.0%}) of detected ENGAGE ticks commanded ZERO "
                    f"horizontal velocity (> {ZERO_CMD_FAIL_FRAC:.0%}). This is the "
                    f"sim's frozen-vworld defect shape -- braking, not steering "
                    f"(audit_per_tick check (e))"))
    else:
        out.append(("OK",
                    f"terminal actuated: {z['n_zero']}/{z['population']} "
                    f"({z['frac']:.0%}) zero-command detected ENGAGE ticks, "
                    f"within the {ZERO_CMD_FAIL_FRAC:.0%} bound"))

    if z.get("n_unparseable_command"):
        out.append(("WARN",
                    f"{z['n_unparseable_command']} detected ENGAGE tick(s) had an "
                    f"unparseable v_north/v_east -- counted, not absorbed"))

    if not s["terminated_in_safe"]:
        out.append(("WARN",
                    f"flight log ends in state {s['terminal_state']!r}, not SAFE "
                    f"-- the log may be truncated (power loss / crash)"))
    return code, out


# ============================================================ reporting


def report(s, path, code, notes):
    w = print
    w(f"== flight log: {path}")
    w(f"   {s['n_ticks']} ticks"
      + (f", t {s['t_start']:.2f}..{s['t_end']:.2f} s "
         f"({s['duration_s']:.2f} s)" if s["duration_s"] is not None else ""))
    for n in s["notes"]:
        w(f"   NOTE: {n}")

    w("")
    w("-- state machine ---------------------------------------------------")
    for t in s["transitions"]:
        t_s = f"{t['t_s']:7.2f}s" if t["t_s"] is not None else "   ?   "
        w(f"   {t_s}  {str(t['from'] or '(start)'):>11} -> {t['to']:<11}"
          f"  streak={t['streak']}"
          + (f"  alt={t['alt_m']:.2f} m" if t["alt_m"] is not None else ""))
    w(f"   ticks per state: "
      + ", ".join(f"{k}={v}" for k, v in sorted(s["state_ticks"].items())))
    w(f"   terminal state : {s['terminal_state']}"
      f"  (terminated_in_safe={s['terminated_in_safe']})")

    w("")
    w("-- failsafes -------------------------------------------------------")
    if s["safe_reasons"]:
        for r in s["safe_reasons"]:
            t_s = f"{r['first_t_s']:7.2f}s" if r["first_t_s"] is not None else "   ?   "
            w(f"   {t_s}  {r['reason']}   (state {r['state']})")
    else:
        w("   none recorded")

    e = s["engage"]
    w("")
    w("-- ENGAGE ----------------------------------------------------------")
    if not e.get("n_ticks"):
        w("   ZERO ENGAGE ticks -- the terminal never ran")
    else:
        w(f"   ticks={e['n_ticks']}  detected={e['n_detected_ticks']}")
        w(f"   sp_source: "
          + ", ".join(f"{k or '(blank)'}={v}" for k, v in sorted(e["sp_source"].items())))
        if e["n_r_hat_present"]:
            w(f"   r_hat: {e['r_hat_max_m']:.2f} -> {e['r_hat_min_m']:.2f} m "
              f"({e['n_r_hat_present']} ticks with a range estimate)")
        else:
            w("   r_hat: NO ticks carried a range estimate")
        if e["abs_lambda_dot_p50"] is not None:
            w(f"   |lambda_dot|: p50={e['abs_lambda_dot_p50']:.2f} "
              f"p95={e['abs_lambda_dot_p95']:.2f} deg/s")
        w(f"   coast={e['n_terminal_coast']}  stale={e['n_stale']}  "
          f"track_broken={e['n_track_broken']}  own_state_bad={e['n_own_state_bad']}")
        if e["health_flags"]:
            w("   health flags: "
              + ", ".join(f"{k}={v}" for k, v in sorted(e["health_flags"].items())))

    z = s["zero_cmd"]
    w("")
    w("-- zero-command ticks (mirrors audit_per_tick check (e)) ------------")
    w(f"   population (detected ENGAGE ticks with a parseable command): "
      f"{z['population']}")
    w(f"   zero-command: {z['n_zero']}"
      + (f"  ({z['frac']:.0%})" if z["frac"] is not None else "")
      + f"   [tol={z['tol']:g}, fail>{z['fail_frac']:.0%}, min_n={z['min_n']}]")
    if z["n_unparseable_command"]:
        w(f"   unparseable command cells: {z['n_unparseable_command']}")

    w("")
    w("-- verdict ---------------------------------------------------------")
    for level, text in notes:
        w(f"   {level:<9} {text}")
    w(f"   EXIT {code} "
      f"({ {0: 'OK', 1: 'FAIL', 2: 'USAGE', 3: 'UNCERTAIN'}[code] })")


# ============================================================ self-test


def self_test() -> int:
    """Offline check: drive the parser over synthetic logs built from the
    PRODUCER's own header when it is importable. Exits 0/1."""
    import tempfile
    fails = []

    def check(cond, msg):
        if cond:
            print(f"  OK   {msg}")
        else:
            print(f"  FAIL {msg}")
            fails.append(msg)

    fields = producer_fields()
    check(fields is not None,
          "flight.deploy.real_flight._CSV_FIELDS is importable (schema source)")
    if fields is None:
        return 1

    def row(**kw):
        d = {k: "" for k in fields}
        d.update(kw)
        return d

    with tempfile.TemporaryDirectory() as td:
        # (1) empty log -> UNCERTAIN, never OK
        p = os.path.join(td, "empty.csv")
        with open(p, "w", newline="") as f:
            csv.DictWriter(f, fieldnames=fields).writeheader()
        h, rows = load_rows(p)
        s = summarize(h, rows)
        code, _ = verdicts(s)
        check(code == EXIT_UNCERTAIN, "an EMPTY log is UNCERTAIN (exit 3), not a pass")
        # ...and the SAME through the CLI. Stopping at verdicts() is why the
        # empty-log KeyError in report() survived every green check: the printer
        # and the --json writer were never driven on this path (2026-07-26).
        jp = os.path.join(td, "empty.json")
        import contextlib
        import io
        with contextlib.redirect_stdout(io.StringIO()):   # keep the report quiet
            rc = main([p, "--json", jp])
        check(rc == EXIT_UNCERTAIN,
              f"main() on an EMPTY log exits {EXIT_UNCERTAIN} UNCERTAIN "
              f"(got {rc}) with no traceback")
        check(os.path.exists(jp)
              and json.load(open(jp))["zero_cmd"]["population"] == 0,
              "the --json summary is still written for an empty log "
              "(zero_cmd.population = 0, not a missing key)")

        # (2) all-zero-command ENGAGE -> FAIL
        p = os.path.join(td, "frozen.csv")
        with open(p, "w", newline="") as f:
            w = csv.DictWriter(f, fieldnames=fields)
            w.writeheader()
            for i in range(20):
                w.writerow(row(t_s=f"{i*0.05:.3f}", state="ENGAGE", streak="5",
                               det_new="1", det_range_m="3.0",
                               v_north="0.0000", v_east="0.0000",
                               v_down="0.0000", yaw_cmd_deg="0.00",
                               sp_source="guided"))
        h, rows = load_rows(p)
        s = summarize(h, rows)
        code, notes = verdicts(s)
        check(code == EXIT_FAIL,
              "an ENGAGE that commanded ZERO horizontal velocity throughout FAILS")
        check(any("DID NOT ACTUATE" in t for _l, t in notes),
              "the failure names the frozen-command defect")

        # (3) a steering ENGAGE -> OK
        p = os.path.join(td, "good.csv")
        with open(p, "w", newline="") as f:
            w = csv.DictWriter(f, fieldnames=fields)
            w.writeheader()
            for i in range(20):
                w.writerow(row(t_s=f"{i*0.05:.3f}", state="ENGAGE", streak="5",
                               det_new="1", det_range_m="3.0",
                               v_north=f"{2.0 + 0.1*i:.4f}", v_east="1.5000",
                               v_down="0.0000", yaw_cmd_deg="0.00",
                               sp_source="guided", r_hat_m="3.000",
                               lambda_dot_deg_s="1.500"))
            w.writerow(row(t_s="1.100", state="SAFE", streak="0",
                           v_north="0.0000", v_east="0.0000", v_down="0.0000",
                           yaw_cmd_deg="0.00", sp_source="safe",
                           safe_reason="breakoff_complete"))
        h, rows = load_rows(p)
        s = summarize(h, rows)
        code, _ = verdicts(s)
        check(code == EXIT_OK, "a steering ENGAGE that ends in SAFE passes")
        check([r["reason"] for r in s["safe_reasons"]] == ["breakoff_complete"],
              "the failsafe reason is recovered from the log")
        check(s["terminated_in_safe"] is True, "terminal state SAFE is detected")

        # (4) underpowered population -> UNCERTAIN, never a silent pass
        p = os.path.join(td, "thin.csv")
        with open(p, "w", newline="") as f:
            w = csv.DictWriter(f, fieldnames=fields)
            w.writeheader()
            for i in range(3):
                w.writerow(row(t_s=f"{i*0.05:.3f}", state="ENGAGE", det_new="1",
                               v_north="0.0000", v_east="0.0000",
                               v_down="0.0000", yaw_cmd_deg="0.00"))
        h, rows = load_rows(p)
        code, _ = verdicts(summarize(h, rows))
        check(code == EXIT_UNCERTAIN,
              "an underpowered zero-command population is UNCERTAIN, not PASS")

        # (5) header drift is caught
        p = os.path.join(td, "drift.csv")
        with open(p, "w", newline="") as f:
            f.write(",".join(fields[:-1]) + "\n")
            f.write(",".join([""] * (len(fields) - 1)) + "\n")
        h, rows = load_rows(p)
        s = summarize(h, rows)
        code, _ = verdicts(s)
        check(code == EXIT_FAIL and s["missing_columns"] == [fields[-1]],
              "a DROPPED producer column is caught as header drift")

    print(f"\nparse_flight_log --self-test: {len(fails)} failure(s)")
    return 1 if fails else 0


# ============================================================ CLI


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description="Summarize a flight/deploy/real_flight.py --log-csv decision log.")
    ap.add_argument("csv_path", nargs="?", help="the per-tick decision CSV")
    ap.add_argument("--json", default=None, help="also write the summary as JSON")
    ap.add_argument("--require-engage", action="store_true",
                    help="treat a flight with zero ENGAGE ticks as a FAILURE "
                         "(use when the pass was supposed to reach the terminal)")
    ap.add_argument("--self-test", action="store_true",
                    help="offline check of this parser; exits 0/1")
    args = ap.parse_args(argv)

    if args.self_test:
        return self_test()
    if not args.csv_path:
        ap.print_usage()
        print("error: a csv_path is required (or --self-test)", file=sys.stderr)
        return EXIT_USAGE

    provenance = _sync_zero_cmd_constants()
    try:
        header, rows = load_rows(args.csv_path)
    except ParseError as e:
        print(f"error: {e}", file=sys.stderr)
        return EXIT_USAGE

    s = summarize(header, rows)
    s["zero_cmd_constants_from"] = provenance
    code, notes = verdicts(s, require_engage=args.require_engage)
    # The JSON is written BEFORE the human report: report() is only a formatter,
    # and a crash in it must not cost the run its machine-readable record (that
    # is exactly what the empty-log KeyError did).
    if args.json:
        s["verdict"] = {"exit": code,
                        "notes": [{"level": l, "text": t} for l, t in notes]}
        with open(args.json, "w") as f:
            json.dump(s, f, indent=2, sort_keys=True)
    report(s, args.csv_path, code, notes)
    if args.json:
        print(f"   [json] {args.json}")
    return code


if __name__ == "__main__":
    sys.exit(main())
