"""Tests for isim.fit_vehicle: segment replay, RMS reporting, and parameter
recovery on synthetic data."""
from dataclasses import replace

import numpy as np
import pytest

from isim.fit_vehicle import (
    _make_synthetic_segment,
    _rms_report,
    _tilt_deg_from_quat,
    fit_vehicle,
    simulate_segment,
)
from isim.vehicle import VehicleParams


def _flat_profile(t, vn=8.0, t0=1.0):
    on = np.where(t < t0, 0.0, 1.0)
    return vn * on, np.zeros_like(t), np.zeros_like(t), np.zeros_like(t)


def test_tilt_deg_from_quat_matches_known_angles():
    # level: no x/y quat component -> 0 deg tilt
    assert _tilt_deg_from_quat(1.0, 0.0, 0.0, 0.0) == pytest.approx(0.0, abs=1e-9)
    # a pure 30 deg pitch (about body y) quaternion: qy = sin(15deg), qw = cos(15deg)
    import math

    half = math.radians(30.0) / 2.0
    tilt = _tilt_deg_from_quat(math.cos(half), 0.0, math.sin(half), 0.0)
    assert tilt == pytest.approx(30.0, abs=1e-6)


def test_simulate_segment_reproduces_its_own_generator_at_matching_dt():
    """Replaying a segment generated by model X through simulate_segment
    with the SAME params X AND the same integration step should reproduce
    it exactly (only float round-trip error). Using a FINER dt_model than
    the generator (the normal, more-accurate default) is expected to differ
    slightly -- that discretization difference is real, not a bug, and is
    exercised separately in test_rms_report_zero_for_self_replay."""
    truth = VehicleParams()
    rng = np.random.default_rng(7)

    def profile(t):
        return _flat_profile(t, vn=6.0, t0=0.5)

    seg = _make_synthetic_segment(truth, profile, duration_s=3.0, dt_log=0.02, noise_rng=rng, noise_std=0.0)
    sim = simulate_segment(truth, seg, dt_model=0.02)  # same step size as the generator
    assert np.allclose(sim["vel_n"], seg["vel_n"], atol=1e-9)
    assert np.allclose(sim["pos_d"], seg["pos_d"], atol=1e-9)


def _replay_as_segment(params, cmd_profile, duration_s, dt_log, dt_model=0.005):
    """Build a 'logged' segment whose truth IS simulate_segment's own output
    at dt_model -- so replaying it with the same params through _rms_report
    (which always uses simulate_segment's default dt_model) is self-
    consistent and should score exactly zero error."""
    n = int(round(duration_s / dt_log)) + 1
    t = np.arange(n) * dt_log
    cmd_vn, cmd_ve, cmd_vd, cmd_yaw = cmd_profile(t)
    stub = {
        "t": t, "cmd_vn": cmd_vn, "cmd_ve": cmd_ve, "cmd_vd": cmd_vd, "cmd_yaw_deg": cmd_yaw,
        "pos_n": np.zeros(n), "pos_e": np.zeros(n), "pos_d": np.zeros(n),
        "vel_n": np.zeros(n), "vel_e": np.zeros(n), "vel_d": np.zeros(n),
    }
    out = simulate_segment(params, stub, dt_model=dt_model)
    return {**stub, **out}


def test_rms_report_zero_for_self_replay_nonzero_for_wrong_params():
    truth = VehicleParams()
    wrong = replace(truth, kp_vel_horiz=truth.kp_vel_horiz * 3.0)
    seg = _replay_as_segment(truth, lambda t: _flat_profile(t, vn=7.0), 3.0, 0.02)
    rms_truth = _rms_report(truth, [seg])
    rms_wrong = _rms_report(wrong, [seg])
    assert rms_truth["vel_n"] < 1e-9
    assert rms_wrong["vel_n"] > 0.1, "a 3x-wrong gain should show up as a real velocity RMS"


def test_fit_vehicle_rejects_unbounded_param_name():
    seg = _make_synthetic_segment(VehicleParams(), _flat_profile, 2.0, 0.02, np.random.default_rng(0), 0.0)
    with pytest.raises(ValueError):
        fit_vehicle([seg], VehicleParams(), free=["not_a_real_param"])


def test_fit_vehicle_noop_with_empty_free_list():
    """free=[] should not error and should return p0 unchanged."""
    seg = _make_synthetic_segment(VehicleParams(), _flat_profile, 2.0, 0.02, np.random.default_rng(0), 0.0)
    p0 = VehicleParams()
    fitted, report = fit_vehicle([seg], p0, free=[])
    assert fitted == p0
    assert report["fitted_values"] == {}
    assert report["rms_before"] == report["rms_after"]


def test_fit_recovers_three_perturbed_params_within_15_percent():
    """The end-to-end recovery check requested for this module: perturb 3
    params away from truth, fit on noisy synthetic segments, and check each
    comes back within 15% of the true value."""
    truth = replace(
        VehicleParams(), tilt_time_constant_s=0.18, drag_linear_horiz=0.6, kp_vel_horiz=2.4
    )
    p0 = replace(
        VehicleParams(), tilt_time_constant_s=0.30, drag_linear_horiz=0.10, kp_vel_horiz=1.0
    )
    free = ["tilt_time_constant_s", "drag_linear_horiz", "kp_vel_horiz"]

    def step_profile(t):
        return _flat_profile(t, vn=10.0, t0=1.0)

    def diag_profile(t):
        on = np.where(t < 0.5, 0.0, 1.0)
        return 6.0 * on, -6.0 * on, np.zeros_like(t), np.zeros_like(t)

    noise_rng = np.random.default_rng(42)
    segs = [
        _make_synthetic_segment(truth, step_profile, 4.0, 0.02, noise_rng, noise_std=0.03),
        _make_synthetic_segment(truth, diag_profile, 4.0, 0.02, noise_rng, noise_std=0.03),
    ]
    fitted, report = fit_vehicle(segs, p0, free)

    for name in free:
        truth_val = getattr(truth, name)
        fitted_val = report["fitted_values"][name]
        pct_err = abs(fitted_val - truth_val) / abs(truth_val)
        assert pct_err < 0.15, f"{name}: {pct_err:.1%} error (truth={truth_val}, fit={fitted_val})"

    # the fit should have materially reduced velocity RMS vs the p0 guess
    assert report["rms_after"]["vel_n"] < 0.2 * report["rms_before"]["vel_n"]


def test_fit_vehicle_holdout_rms_reported_and_reasonable():
    truth = replace(VehicleParams(), kp_vel_horiz=2.0)
    p0 = replace(VehicleParams(), kp_vel_horiz=0.8)
    noise_rng = np.random.default_rng(11)
    fit_segs = [
        _make_synthetic_segment(truth, lambda t: _flat_profile(t, vn=8.0), 3.0, 0.02, noise_rng, 0.02)
    ]
    holdout_segs = [
        _make_synthetic_segment(truth, lambda t: _flat_profile(t, vn=4.0), 3.0, 0.02, noise_rng, 0.02)
    ]
    fitted, report = fit_vehicle(fit_segs, p0, free=["kp_vel_horiz"], holdout_segments=holdout_segs)
    assert "rms_holdout" in report
    assert report["rms_holdout"]["vel_n"] < report["rms_before"]["vel_n"]
