"""GOLDEN CONTRACT + MUTANT tests for scripts/rescore_cpa.py (issue #8).

  PRODUCER  scripts/m4_intercept.py -- CSV_HEADER and write_row_m4, the module's
            OWN writer. The fixture flight CSV is generated by calling that
            writer on synthetic ticks; it is NEVER hand-typed. Hand-typed
            fixtures are exactly what let both 2026-07-24 schema breaks pass
            every unit test while the real producer/consumer pair returned
            garbage.
  CONSUMER  scripts/rescore_cpa.py -- the standalone CPA re-scorer.

THE FIXTURE GEOMETRY (chosen so all four answers are different, which is the
only way a scorer's reference and its interpolation can both be pinned):

  * body yaw is due world-+x, psi = 90 deg, so the camera lever
    (0.120 fwd, 0.030 left, 0.002 up) lands on world (+0.120, +0.030, +0.002)
  * the airframe centre flies +x through the ticks ... -0.30, +0.30 ...
    (0.6 m apart) at constant y = 0, z = 1.0
  * the target is static at (0.0, 0.30, 1.0)

  => centre, interpolated  = 0.3000 m  (the true CPA, BETWEEN two ticks)
     centre, logged tick   = 0.4243 m  (sqrt(0.30^2 + 0.30^2))
     lens,   logged tick   = 0.3245 m
     lens,   interpolated  = 0.2700 m

THE MUTANT (required by issue #8): re-pointing the scorer at gt_cam_* -- i.e.
zeroing the lever arm so the airframe centre collapses back onto the camera --
must make the primary assertion FAIL. test_mutant_lens_reference_fails runs
that mutation for real (it rewrites the module source, imports the mutant, and
re-runs the assertions), so this file cannot go green on a scorer that silently
kept measuring the lens.

Offline; no sim. Run:
  .venv/bin/python -m pytest tests/test_rescore_cpa.py -v
"""
import csv
import importlib.util
import math
import os
import sys
import types

import pytest

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRIPTS = os.path.join(REPO_ROOT, "scripts")
for p in (SCRIPTS, os.path.dirname(os.path.abspath(__file__))):
    if p not in sys.path:
        sys.path.insert(0, p)

import rescore_cpa  # noqa: E402


# ------------------------------------------------------------------ producer --


def _import_m4():
    """The PRODUCER module. Never skipped: if the gz/mavsdk bindings are absent
    (CI's OSRF apt step is best-effort) they are stubbed so the REAL
    write_row_m4/CSV_HEADER still run -- green must mean the contract ran."""
    try:
        import m4_intercept
        return m4_intercept
    except ImportError:
        pass
    for name in ("gz", "gz.transport13", "gz.msgs10", "gz.msgs10.image_pb2",
                 "gz.msgs10.pose_v_pb2", "gz.msgs10.clock_pb2",
                 "gz.msgs10.double_pb2", "mavsdk", "mavsdk.action",
                 "mavsdk.offboard", "mavsdk.telemetry", "cv2", "numpy"):
        if name not in sys.modules:
            mod = types.ModuleType(name)
            mod.__getattr__ = lambda _n: type("_S", (), {})  # noqa: E731
            sys.modules[name] = mod
    import m4_intercept  # noqa: F811
    return m4_intercept


M4 = _import_m4()


# ------------------------------------------------------------------- fixture --

PAD_CAM = (rescore_cpa.CAM_FWD_M, rescore_cpa.CAM_LEFT_M, 0.2290)
PSI_DEG = 90.0                       # body +x, with the pad datum also 90
BASE_Z = 1.0
TGT = (0.0, 0.30, 1.0)
STEP_M = 0.6
X0 = -6.3                            # ticks land on ..., -0.3, +0.3, ...
N_DASH = 17

EXPECT_CENTRE_INTERP = 0.30
EXPECT_CENTRE_LOGGED = math.hypot(0.30, 0.30)
EXPECT_LENS_LOGGED = math.sqrt(0.18 ** 2 + 0.27 ** 2 + 0.002 ** 2)
EXPECT_LENS_INTERP = math.hypot(0.27, 0.002)


def _write_fixture(path, blank_gt=False, drop_column=None):
    """A flight CSV written THROUGH the producer's own writer."""
    header = list(M4.CSV_HEADER)
    if drop_column:
        header.remove(drop_column)
    with open(path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(header)
        rows = []
        t = 0.0
        for _ in range(5):                              # on the pad
            rows.append(("TAKEOFF", PAD_CAM, 0.0))
            t += 0.2
        for i in range(N_DASH):                         # the dash
            bx = X0 + STEP_M * i
            cam = (bx + rescore_cpa.CAM_FWD_M,
                   0.0 + rescore_cpa.CAM_LEFT_M,
                   BASE_Z + rescore_cpa.CAM_UP_M)
            rows.append(("CODED_DASH", cam,
                         BASE_Z - (PAD_CAM[2] - rescore_cpa.CAM_UP_M)))
        # the producer's writer decides the schema, the formatting and the
        # blank-field convention -- this test never formats a number itself.
        buf = []

        class _Sink:
            def writerow(self, row):
                buf.append(row)

        class _F:
            def flush(self):
                pass

        tt = 0.0
        for phase, cam, alt in rows:
            gt_cam = None if blank_gt else cam
            gt_range = (None if blank_gt else
                        math.dist(cam, TGT))
            M4.write_row_m4(
                _Sink(), _F(), tt, phase, "pronav", False, None,
                PSI_DEG, None, None, None, None, None, None, None,
                (0.0, 0.0, 0.0, 0.0), alt,
                gt_cam, None if blank_gt else TGT, gt_range,
            )
            tt += 0.05
        idx = {c: i for i, c in enumerate(M4.CSV_HEADER)}
        for row in buf:
            if drop_column:
                row = [v for i, v in enumerate(row) if i != idx[drop_column]]
            writer.writerow(row)
    return path


def _scored(path, module=rescore_cpa):
    fl = module.Flight(path)
    fl.load()
    return fl


# ------------------------------------------------------------------- tests ---


def test_fixture_comes_from_the_producers_own_schema(tmp_path):
    p = _write_fixture(str(tmp_path / "flight.csv"))
    with open(p) as f:
        header = next(csv.reader(f))
    assert header == list(M4.CSV_HEADER), (
        "the fixture header drifted from m4_intercept.CSV_HEADER -- the "
        "producer schema moved; update this contract WITH it")
    with open(p) as f:
        rows = list(csv.DictReader(f))
    assert len(rows) == 5 + N_DASH
    for col in rescore_cpa.REQUIRED_COLS:
        assert col in header, f"producer no longer writes {col}"
        assert any(r[col] for r in rows), f"{col} is blank on every row"


def test_lever_arm_matches_the_documented_sdf_chain():
    """camera_link - base_link, from the two poses the module documents."""
    assert rescore_cpa.CAM_UP_M == pytest.approx(
        rescore_cpa.CAM_ABOVE_MODEL_M - rescore_cpa.BASE_ABOVE_MODEL_M, abs=1e-9)
    assert rescore_cpa.CAM_UP_M < 0.01, (
        "the camera sits ~2 mm above base_link; a lever of 0.208/0.242 m is the "
        "landing-gear height / the model-origin offset, not the camera lever")


def test_ram_radius_is_ratified_and_not_a_flag():
    assert rescore_cpa.RAM_RADIUS_M == 0.35        # ADR-0084
    src = open(os.path.join(SCRIPTS, "rescore_cpa.py")).read()
    assert "--radius" not in src and "--ram" not in src, (
        "the ram radius must not be tunable from the CLI -- ADR-0084 ratified "
        "0.35 m and a ruler fix must never be 'balanced' by moving it")


def test_segment_minimum_is_the_closed_form():
    d0, d1 = (0.30, 0.30, 0.0), (-0.30, 0.30, 0.0)
    got = rescore_cpa._seg_min(d0, d1)
    assert got is not None
    assert got[0] == pytest.approx(0.30, abs=1e-12)
    assert got[1] == pytest.approx(0.5, abs=1e-12)
    assert rescore_cpa._seg_min((1.0, 0.0, 0.0), (1.0, 0.0, 0.0)) is None
    assert rescore_cpa._seg_min((1.0, 0.0, 0.0), (2.0, 0.0, 0.0)) is None


def test_primary_ruler_is_centre_interpolated(tmp_path):
    """THE MUTANT-BEARING ASSERTION. The scorer's primary output must equal the
    CENTRE-based INTERPOLATED value, and differ from BOTH the lens-based value
    and the logged-tick value."""
    fl = _scored(_write_fixture(str(tmp_path / "flight.csv")))
    assert fl.pad_source == "pad-calibrated"
    centre = fl.cpa(rescore_cpa.PRIMARY_MODE)
    lens = fl.cpa("lens")

    assert centre["interp_m"] == pytest.approx(EXPECT_CENTRE_INTERP, abs=1e-4)
    assert centre["logged_m"] == pytest.approx(EXPECT_CENTRE_LOGGED, abs=1e-4)
    assert lens["logged_m"] == pytest.approx(EXPECT_LENS_LOGGED, abs=1e-4)
    assert lens["interp_m"] == pytest.approx(EXPECT_LENS_INTERP, abs=1e-4)

    # ... and the three must be mutually distinct, or the test proves nothing
    assert abs(centre["interp_m"] - lens["logged_m"]) > 0.01
    assert abs(centre["interp_m"] - lens["interp_m"]) > 0.01
    assert abs(centre["interp_m"] - centre["logged_m"]) > 0.01
    assert centre["interp_segment"] is not None      # the CPA is BETWEEN ticks
    # the fixture teleports once (pad -> start of the dash), which is exactly
    # what the long-segment guard is for: it must COUNT it and must not let the
    # CPA be claimed on it.
    assert centre["long_segments"] == 1
    assert centre["interp_on_long_segment"] is False


def test_tilt_mode_agrees_with_level_mode_on_a_level_fixture(tmp_path):
    fl = _scored(_write_fixture(str(tmp_path / "flight.csv")))
    assert fl.cpa("centre-tilt")["interp_m"] == pytest.approx(
        fl.cpa("centre")["interp_m"], abs=2e-3)


def test_yaw_datum_is_calibrated_from_the_pad(tmp_path):
    fl = _scored(_write_fixture(str(tmp_path / "flight.csv")))
    assert fl.yaw_offset_deg == pytest.approx(PSI_DEG, abs=0.05)
    assert fl.yaw_check_deg == pytest.approx(0.0, abs=0.5)


# --- no vacuous verdicts / fail closed ---------------------------------------


def test_blank_ground_truth_is_a_hard_error_not_a_number(tmp_path):
    p = _write_fixture(str(tmp_path / "blank.csv"), blank_gt=True)
    with pytest.raises(rescore_cpa.HardError) as e:
        _scored(p)
    assert "0 usable ticks" in str(e.value) and "blank.csv" in str(e.value)


def test_missing_column_names_the_column(tmp_path):
    p = _write_fixture(str(tmp_path / "nocol.csv"), drop_column="gt_cam_z")
    with pytest.raises(rescore_cpa.HardError) as e:
        _scored(p)
    assert "gt_cam_z" in str(e.value)


def test_missing_file_and_empty_file_are_hard_errors(tmp_path):
    with pytest.raises(rescore_cpa.HardError):
        _scored(str(tmp_path / "nope.csv"))
    empty = tmp_path / "empty.csv"
    empty.write_text("")
    with pytest.raises(rescore_cpa.HardError):
        _scored(str(empty))


def test_summarise_refuses_zero_units():
    with pytest.raises(rescore_cpa.HardError):
        rescore_cpa.summarise([])


def test_exact_mode_refuses_historical_logs(tmp_path):
    fl = _scored(_write_fixture(str(tmp_path / "flight.csv")))
    assert fl.has_exact is False
    with pytest.raises(rescore_cpa.HardError) as e:
        fl.cpa("exact")
    assert "gt_intc" in str(e.value)


# --- THE MUTANT ---------------------------------------------------------------


def _load_mutant(tmp_path, old, new, name):
    """Import a source-level MUTATION of rescore_cpa as its own module."""
    src = open(os.path.join(SCRIPTS, "rescore_cpa.py")).read()
    assert old in src, f"mutation target {old!r} not found -- the code moved"
    mpath = tmp_path / f"{name}.py"
    mpath.write_text(src.replace(old, new, 1))
    spec = importlib.util.spec_from_file_location(name, str(mpath))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_mutant_lens_reference_fails(tmp_path):
    """Restore the DEFECT -- point the scorer back at gt_cam_* by collapsing the
    lever arm to zero -- and the primary assertion must FAIL."""
    mut = _load_mutant(tmp_path,
                       "CAM_FWD_M = 0.120\nCAM_LEFT_M = 0.030\nCAM_UP_M = 0.002",
                       "CAM_FWD_M = 0.0\nCAM_LEFT_M = 0.0\nCAM_UP_M = 0.0",
                       "rescore_cpa_mutant_lens")
    p = _write_fixture(str(tmp_path / "flight.csv"))
    fl = mut.Flight(p)
    fl.load()
    centre = fl.cpa(mut.PRIMARY_MODE)
    lens = fl.cpa("lens")
    # the defect's signature: the "centre" ruler IS the lens ruler again
    assert centre["interp_m"] == pytest.approx(lens["interp_m"], abs=1e-9)
    assert centre["interp_m"] != pytest.approx(EXPECT_CENTRE_INTERP, abs=1e-4)
    with pytest.raises(AssertionError):
        assert centre["interp_m"] == pytest.approx(EXPECT_CENTRE_INTERP, abs=1e-4)


def test_mutant_logged_tick_only_fails(tmp_path):
    """Restore the OTHER half of the defect -- take the smallest logged tick
    instead of the true minimum between ticks -- and the primary must FAIL."""
    mut = _load_mutant(tmp_path,
                       "    if not (0.0 < s < 1.0):\n        return None",
                       "    if True:\n        return None",
                       "rescore_cpa_mutant_logged")
    p = _write_fixture(str(tmp_path / "flight.csv"))
    fl = mut.Flight(p)
    fl.load()
    centre = fl.cpa(mut.PRIMARY_MODE)
    assert centre["interp_m"] == pytest.approx(centre["logged_m"], abs=1e-9)
    with pytest.raises(AssertionError):
        assert centre["interp_m"] == pytest.approx(EXPECT_CENTRE_INTERP, abs=1e-4)


# --- end-to-end on the real arm indices ---------------------------------------


def test_gate_arms_exist_and_the_legacy_table_reproduces():
    """The acceptance gate itself, run through the shipped entry point."""
    for arm in rescore_cpa.GATE_ARMS:
        if not os.path.exists(os.path.join(REPO_ROOT, arm)):
            pytest.fail(f"gate arm missing: {arm} (the gate cannot be vacuous)")
    ok, notes, results, pooled = rescore_cpa.gate(
        [m for m in rescore_cpa.MODES if m != "exact"])
    assert ok, f"legacy ad-hoc table did not reproduce: {notes}"
    assert pooled["lens"]["logged"]["n"] == 16
    # and the CORRECTED ruler must differ from the published one -- if it does
    # not, the fix is inert.
    assert abs(pooled["centre"]["interp"]["median_hi"]
               - pooled["adhoc-published"]["interp"]["median_hi"]) > 0.05
