"""GOLDEN CONTRACT + MUTANT tests for scripts/rescore_cpa.py (issue #8).

  PRODUCER  scripts/m4_intercept.py -- CSV_HEADER and write_row_m4, the module's
            OWN writer. The fixture flight CSV is generated by calling that
            writer on synthetic ticks; it is NEVER hand-typed. Hand-typed
            fixtures are exactly what let both 2026-07-24 schema breaks pass
            every unit test while the real producer/consumer pair returned
            garbage.
  CONSUMER  scripts/rescore_cpa.py -- the standalone CPA re-scorer.

THE FIXTURE GEOMETRY (chosen so all four answers are different, which is the
only way a scorer's reference and its interpolation can both be pinned):

  * body yaw is due world-+x, psi = 90 deg, so the camera lever
    (0.120 fwd, 0.030 left, 0.002 up) lands on world (+0.120, +0.030, +0.002)
  * the airframe centre flies +x through the ticks ... -0.30, +0.30 ...
    (0.6 m apart) at constant y = 0, z = 1.0
  * the target is static at (0.0, 0.30, 1.0)

  => centre, interpolated  = 0.3000 m  (the true CPA, BETWEEN two ticks)
     centre, logged tick   = 0.4243 m  (sqrt(0.30^2 + 0.30^2))
     lens,   logged tick   = 0.3245 m
     lens,   interpolated  = 0.2700 m

THE MUTANT (required by issue #8): re-pointing the scorer at gt_cam_* -- i.e.
zeroing the lever arm so the airframe centre collapses back onto the camera --
must make the primary assertion FAIL. test_mutant_lens_reference_fails runs
that mutation for real (it rewrites the module source, imports the mutant, and
re-runs the assertions), so this file cannot go green on a scorer that silently
kept measuring the lens.

Offline; no sim. Run:
  .venv/bin/python -m pytest tests/test_rescore_cpa.py -v
"""
import csv
import importlib.util
import math
import os
import sys

import pytest

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRIPTS = os.path.join(REPO_ROOT, "scripts")
for p in (SCRIPTS, os.path.dirname(os.path.abspath(__file__))):
    if p not in sys.path:
        sys.path.insert(0, p)

import rescore_cpa  # noqa: E402


# ------------------------------------------------------------------ producer --


def _import_m4():
    """The PRODUCER module. Never skipped: if the gz/mavsdk bindings are absent
    (CI's OSRF apt step is best-effort) they are stubbed so the REAL
    write_row_m4/CSV_HEADER still run -- green must mean the contract ran.

    MOVED OUT 2026-09-16 (docs/next.md item 4). The stub meta-path finder used
    to be built and APPENDED right here, at this module's scope. It worked, but
    `sys.meta_path` is PROCESS-WIDE state, so it also silently fixed the import
    for every test module collected after this one alphabetically and for none
    collected before -- four other files depended on that ordering. It now lives
    in the repo-root `conftest.py`, which pytest imports before collecting
    anything, so the behaviour is deterministic. That file documents the three
    properties the finder has to keep (real bindings win, it never raises, stub
    packages carry __path__)."""
    try:
        import m4_intercept
        return m4_intercept
    except ImportError as exc:                 # pragma: no cover - env failure
        raise RuntimeError(
            "could not import the PRODUCER module scripts/m4_intercept.py. If "
            "this says 'No module named gz' (or mavsdk), the repo-root "
            "conftest.py did not install its stub finder -- pytest was probably "
            "run from inside tests/ instead of the repo root. Run it as "
            "scripts/run_tests.sh does: `.venv/bin/python -m pytest "
            "tests/test_rescore_cpa.py -v` from the repo root."
        ) from exc


M4 = _import_m4()


# ------------------------------------------------------------------- fixture --

PAD_CAM = (rescore_cpa.CAM_FWD_M, rescore_cpa.CAM_LEFT_M, 0.2290)
PSI_DEG = 90.0                       # body +x, with the pad datum also 90
BASE_Z = 1.0
TGT = (0.0, 0.30, 1.0)
STEP_M = 0.6
X0 = -6.3                            # ticks land on ..., -0.3, +0.3, ...
N_DASH = 17

EXPECT_CENTRE_INTERP = 0.30
EXPECT_CENTRE_LOGGED = math.hypot(0.30, 0.30)
EXPECT_LENS_LOGGED = math.sqrt(0.18 ** 2 + 0.27 ** 2 + 0.002 ** 2)
EXPECT_LENS_INTERP = math.hypot(0.27, 0.002)


def _write_fixture(path, blank_gt=False, drop_column=None):
    """A flight CSV written THROUGH the producer's own writer."""
    header = list(M4.CSV_HEADER)
    if drop_column:
        header.remove(drop_column)
    with open(path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(header)
        rows = []
        t = 0.0
        for _ in range(5):                              # on the pad
            rows.append(("TAKEOFF", PAD_CAM, 0.0))
            t += 0.2
        for i in range(N_DASH):                         # the dash
            bx = X0 + STEP_M * i
            cam = (bx + rescore_cpa.CAM_FWD_M,
                   0.0 + rescore_cpa.CAM_LEFT_M,
                   BASE_Z + rescore_cpa.CAM_UP_M)
            rows.append(("CODED_DASH", cam,
                         BASE_Z - (PAD_CAM[2] - rescore_cpa.CAM_UP_M)))
        # the producer's writer decides the schema, the formatting and the
        # blank-field convention -- this test never formats a number itself.
        buf = []

        class _Sink:
            def writerow(self, row):
                buf.append(row)

        class _F:
            def flush(self):
                pass

        tt = 0.0
        for phase, cam, alt in rows:
            gt_cam = None if blank_gt else cam
            gt_range = (None if blank_gt else
                        math.dist(cam, TGT))
            M4.write_row_m4(
                _Sink(), _F(), tt, phase, "pronav", False, None,
                PSI_DEG, None, None, None, None, None, None, None,
                (0.0, 0.0, 0.0, 0.0), alt,
                gt_cam, None if blank_gt else TGT, gt_range,
            )
            tt += 0.05
        idx = {c: i for i, c in enumerate(M4.CSV_HEADER)}
        for row in buf:
            if drop_column:
                row = [v for i, v in enumerate(row) if i != idx[drop_column]]
            writer.writerow(row)
    return path


def _scored(path, module=rescore_cpa):
    fl = module.Flight(path)
    fl.load()
    return fl


# ------------------------------------------------------------------- tests ---


def test_fixture_comes_from_the_producers_own_schema(tmp_path):
    p = _write_fixture(str(tmp_path / "flight.csv"))
    with open(p) as f:
        header = next(csv.reader(f))
    assert header == list(M4.CSV_HEADER), (
        "the fixture header drifted from m4_intercept.CSV_HEADER -- the "
        "producer schema moved; update this contract WITH it")
    with open(p) as f:
        rows = list(csv.DictReader(f))
    assert len(rows) == 5 + N_DASH
    for col in rescore_cpa.REQUIRED_COLS:
        assert col in header, f"producer no longer writes {col}"
        assert any(r[col] for r in rows), f"{col} is blank on every row"


def test_lever_arm_matches_the_documented_sdf_chain():
    """camera_link - base_link, from the two poses the module documents."""
    assert rescore_cpa.CAM_UP_M == pytest.approx(
        rescore_cpa.CAM_ABOVE_MODEL_M - rescore_cpa.BASE_ABOVE_MODEL_M, abs=1e-9)
    assert rescore_cpa.CAM_UP_M < 0.01, (
        "the camera sits ~2 mm above base_link; a lever of 0.208/0.242 m is the "
        "landing-gear height / the model-origin offset, not the camera lever")


def test_ram_radius_is_ratified_and_not_a_flag():
    assert rescore_cpa.RAM_RADIUS_M == 0.35        # ADR-0084
    src = open(os.path.join(SCRIPTS, "rescore_cpa.py")).read()
    assert "--radius" not in src and "--ram" not in src, (
        "the ram radius must not be tunable from the CLI -- ADR-0084 ratified "
        "0.35 m and a ruler fix must never be 'balanced' by moving it")


def test_segment_minimum_is_the_closed_form():
    d0, d1 = (0.30, 0.30, 0.0), (-0.30, 0.30, 0.0)
    got = rescore_cpa._seg_min(d0, d1)
    assert got is not None
    assert got[0] == pytest.approx(0.30, abs=1e-12)
    assert got[1] == pytest.approx(0.5, abs=1e-12)
    assert rescore_cpa._seg_min((1.0, 0.0, 0.0), (1.0, 0.0, 0.0)) is None
    assert rescore_cpa._seg_min((1.0, 0.0, 0.0), (2.0, 0.0, 0.0)) is None


def test_primary_ruler_is_centre_interpolated(tmp_path):
    """THE MUTANT-BEARING ASSERTION. The scorer's primary output must equal the
    CENTRE-based INTERPOLATED value, and differ from BOTH the lens-based value
    and the logged-tick value."""
    fl = _scored(_write_fixture(str(tmp_path / "flight.csv")))
    assert fl.pad_source == "pad-calibrated"
    centre = fl.cpa(rescore_cpa.PRIMARY_MODE)
    lens = fl.cpa("lens")

    assert centre["interp_m"] == pytest.approx(EXPECT_CENTRE_INTERP, abs=1e-4)
    assert centre["logged_m"] == pytest.approx(EXPECT_CENTRE_LOGGED, abs=1e-4)
    assert lens["logged_m"] == pytest.approx(EXPECT_LENS_LOGGED, abs=1e-4)
    assert lens["interp_m"] == pytest.approx(EXPECT_LENS_INTERP, abs=1e-4)

    # ... and the three must be mutually distinct, or the test proves nothing
    assert abs(centre["interp_m"] - lens["logged_m"]) > 0.01
    assert abs(centre["interp_m"] - lens["interp_m"]) > 0.01
    assert abs(centre["interp_m"] - centre["logged_m"]) > 0.01
    assert centre["interp_segment"] is not None      # the CPA is BETWEEN ticks
    # the fixture teleports once (pad -> start of the dash), which is exactly
    # what the long-segment guard is for: it must COUNT it and must not let the
    # CPA be claimed on it.
    assert centre["long_segments"] == 1
    assert centre["interp_on_long_segment"] is False


def test_tilt_mode_agrees_with_level_mode_on_a_level_fixture(tmp_path):
    fl = _scored(_write_fixture(str(tmp_path / "flight.csv")))
    assert fl.cpa("centre-tilt")["interp_m"] == pytest.approx(
        fl.cpa("centre")["interp_m"], abs=2e-3)


def test_yaw_datum_is_calibrated_from_the_pad(tmp_path):
    fl = _scored(_write_fixture(str(tmp_path / "flight.csv")))
    assert fl.yaw_offset_deg == pytest.approx(PSI_DEG, abs=0.05)
    assert fl.yaw_check_deg == pytest.approx(0.0, abs=0.5)


# --- no vacuous verdicts / fail closed ---------------------------------------


def test_blank_ground_truth_is_a_hard_error_not_a_number(tmp_path):
    p = _write_fixture(str(tmp_path / "blank.csv"), blank_gt=True)
    with pytest.raises(rescore_cpa.HardError) as e:
        _scored(p)
    assert "0 usable ticks" in str(e.value) and "blank.csv" in str(e.value)


def test_missing_column_names_the_column(tmp_path):
    p = _write_fixture(str(tmp_path / "nocol.csv"), drop_column="gt_cam_z")
    with pytest.raises(rescore_cpa.HardError) as e:
        _scored(p)
    assert "gt_cam_z" in str(e.value)


def test_missing_file_and_empty_file_are_hard_errors(tmp_path):
    with pytest.raises(rescore_cpa.HardError):
        _scored(str(tmp_path / "nope.csv"))
    empty = tmp_path / "empty.csv"
    empty.write_text("")
    with pytest.raises(rescore_cpa.HardError):
        _scored(str(empty))


def test_summarise_refuses_zero_units():
    with pytest.raises(rescore_cpa.HardError):
        rescore_cpa.summarise([])


def test_exact_mode_refuses_historical_logs(tmp_path):
    fl = _scored(_write_fixture(str(tmp_path / "flight.csv")))
    assert fl.has_exact is False
    with pytest.raises(rescore_cpa.HardError) as e:
        fl.cpa("exact")
    assert "gt_intc" in str(e.value)


# --- THE MUTANT ---------------------------------------------------------------


def _load_mutant(tmp_path, old, new, name):
    """Import a source-level MUTATION of rescore_cpa as its own module."""
    src = open(os.path.join(SCRIPTS, "rescore_cpa.py")).read()
    assert old in src, f"mutation target {old!r} not found -- the code moved"
    mpath = tmp_path / f"{name}.py"
    mpath.write_text(src.replace(old, new, 1))
    spec = importlib.util.spec_from_file_location(name, str(mpath))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_mutant_lens_reference_fails(tmp_path):
    """Restore the DEFECT -- point the scorer back at gt_cam_* by collapsing the
    lever arm to zero -- and the primary assertion must FAIL."""
    mut = _load_mutant(tmp_path,
                       "CAM_FWD_M = 0.120\nCAM_LEFT_M = 0.030\nCAM_UP_M = 0.002",
                       "CAM_FWD_M = 0.0\nCAM_LEFT_M = 0.0\nCAM_UP_M = 0.0",
                       "rescore_cpa_mutant_lens")
    p = _write_fixture(str(tmp_path / "flight.csv"))
    fl = mut.Flight(p)
    fl.load()
    centre = fl.cpa(mut.PRIMARY_MODE)
    lens = fl.cpa("lens")
    # the defect's signature: the "centre" ruler IS the lens ruler again
    assert centre["interp_m"] == pytest.approx(lens["interp_m"], abs=1e-9)
    assert centre["interp_m"] != pytest.approx(EXPECT_CENTRE_INTERP, abs=1e-4)
    with pytest.raises(AssertionError):
        assert centre["interp_m"] == pytest.approx(EXPECT_CENTRE_INTERP, abs=1e-4)


def test_mutant_logged_tick_only_fails(tmp_path):
    """Restore the OTHER half of the defect -- take the smallest logged tick
    instead of the true minimum between ticks -- and the primary must FAIL."""
    mut = _load_mutant(tmp_path,
                       "    if not (0.0 < s < 1.0):\n        return None",
                       "    if True:\n        return None",
                       "rescore_cpa_mutant_logged")
    p = _write_fixture(str(tmp_path / "flight.csv"))
    fl = mut.Flight(p)
    fl.load()
    centre = fl.cpa(mut.PRIMARY_MODE)
    assert centre["interp_m"] == pytest.approx(centre["logged_m"], abs=1e-9)
    with pytest.raises(AssertionError):
        assert centre["interp_m"] == pytest.approx(EXPECT_CENTRE_INTERP, abs=1e-4)


# --- end-to-end on the real arm indices ---------------------------------------


def test_gate_arms_exist_and_the_legacy_table_reproduces():
    """The acceptance gate itself, run through the shipped entry point."""
    for arm in rescore_cpa.GATE_ARMS:
        if not os.path.exists(os.path.join(REPO_ROOT, arm)):
            pytest.fail(f"gate arm missing: {arm} (the gate cannot be vacuous)")
    # The gate follows each arm row's flight_csv_path to the per-tick flight
    # CSVs -- gitignored, machine-local bulk logs (the 168-flight archive).
    # Where that archive is absent (CI, any fresh clone) the gate CANNOT run
    # and must say so as a skip -- not fail the suite (this one assertion kept
    # CI red for every run from 2026-08-11 to 2026-08-13) and not pass
    # vacuously. On the dev machine the archive exists, the skip never fires,
    # and the gate still runs for real. The skip reason is named in
    # ALLOWED_SKIPS in scripts/run_tests.sh.
    with open(os.path.join(REPO_ROOT, rescore_cpa.GATE_ARMS[0])) as fh:
        first_row = next(csv.DictReader(r for r in fh if not r.startswith("#")))
    if not os.path.exists(first_row["flight_csv_path"]):
        pytest.skip("per-tick flight CSV archive not on this machine "
                    "(gitignored machine-local data; the rescore gate can only "
                    "run where the 168-flight archive exists)")
    ok, notes, results, pooled = rescore_cpa.gate(
        [m for m in rescore_cpa.MODES if m != "exact"])
    assert ok, f"legacy ad-hoc table did not reproduce: {notes}"
    assert pooled["lens"]["logged"]["n"] == 16
    # and the CORRECTED ruler must differ from the published one -- if it does
    # not, the fix is inert.
    assert abs(pooled["centre"]["interp"]["median_hi"]
               - pooled["adhoc-published"]["interp"]["median_hi"]) > 0.05


# ------------------------------------------------ attitude columns (3b) ---
# 2026-09-16, docs/next.md 3b. They live in THIS file because it owns the
# producer import (M4); a second importer would add to the collection-order
# coupling pinned in test_ci_gz_deselect_list.py.


def _one_row(att_quat):
    buf = []

    class _Sink:
        def writerow(self, row):
            buf.append(row)

    class _F:
        def flush(self):
            pass

    M4.write_row_m4(
        _Sink(), _F(), 0.0, "CODED_DASH", "pronav", False, None,
        PSI_DEG, None, None, None, None, None, None, None,
        (0.0, 0.0, 0.0, 0.0), 0.5, PAD_CAM, TGT, 1.0, att_quat=att_quat)
    assert len(buf) == 1
    assert len(buf[0]) == len(M4.CSV_HEADER), "row and header disagree on width"
    return dict(zip(M4.CSV_HEADER, buf[0]))


def test_attitude_is_logged_through_the_producer():
    # 20 deg nose-DOWN about body y (a dash attitude), no roll, no yaw.
    half = math.radians(-20.0) / 2.0
    row = _one_row((math.cos(half), 0.0, math.sin(half), 0.0))
    assert float(row["att_pitch_deg"]) == pytest.approx(-20.0, abs=1e-3)
    assert float(row["att_roll_deg"]) == pytest.approx(0.0, abs=1e-3)
    assert float(row["att_qw"]) == pytest.approx(math.cos(half), abs=1e-6)
    # 15 deg right-wing-down roll about body x.
    half = math.radians(15.0) / 2.0
    row = _one_row((math.cos(half), math.sin(half), 0.0, 0.0))
    assert float(row["att_roll_deg"]) == pytest.approx(15.0, abs=1e-3)
    assert float(row["att_pitch_deg"]) == pytest.approx(0.0, abs=1e-3)


def test_missing_attitude_is_blank_not_level():
    row = _one_row(None)
    for col in ("att_qw", "att_qx", "att_qy", "att_qz",
                "att_roll_deg", "att_pitch_deg"):
        assert row[col] == "", f"{col} must be BLANK with no sample, got {row[col]!r}"


# --------------------------------------------- the altitude reference offset --
#
# `--alt-ref-offset-m` (default 0.0) shifts the altitude reference the hold and
# the takeoff aim at. Its whole reason to exist is that two height datums were
# never lined up: the vehicle regulates its RELATIVE altitude (`alt_m`, above
# the arm point) to ALT_REF_M = 0.5 while the target's centre sits at world
# z = 0.5. `alt_m` reads 0.000 with the aircraft still on its LANDING GEAR, so
# the camera ends up ~0.229 m above that datum -- GEAR REST HEIGHT, not a
# camera boom (the camera is 2 mm above base_link; ADR-0095, and the constants
# BASE_REST_ABOVE_GROUND_M / CAM_UP_M in the scorer this file tests) -- so in
# hover the lens is ~0.16-0.20 m above the target centre, and the same ~0.20 m
# turns up as the vertical component of closest approach (measured in flight
# 2026-09-16, docs/next.md item 3; pre-registered in
# docs/vertical_channel_prereg.md section 9).
#
# These tests PROVE the default is behaviour-identical rather than asserting
# it, and the two mutant-style tests below fail if the offset is ignored --
# either inside the helper, or at any of the altitude-hold sites.


def _args_from_cli(argv_tail):
    """The REAL parser, so the DEFAULT under test is the shipped default and
    not a value re-typed into the test (the hand-typed-fixture trap)."""
    argv = ["m4_intercept.py", "--law", "pronav"] + list(argv_tail)
    old = sys.argv
    sys.argv = argv
    try:
        return M4.parse_args()
    finally:
        sys.argv = old


def test_alt_ref_default_is_identity():
    args = _args_from_cli([])
    assert args.alt_ref_offset_m == 0.0, "the shipped default must be 0.0"
    # EXACT equality, not approx: 0.5 + 0.0 is 0.5 in IEEE-754, and "byte
    # identical when off" is the claim this project makes about every new flag.
    assert M4.alt_ref_m(args) == M4.ALT_REF_M


def test_alt_ref_default_leaves_the_hold_command_untouched():
    args = _args_from_cli([])
    alt_ref = M4.alt_ref_m(args)
    for alt_m in (0.0, 0.25, 0.5, 0.62, 1.4):
        off = M4.acquire_command(False, None, alt_m, 0.0, alt_ref=alt_ref)
        bare = M4.acquire_command(False, None, alt_m, 0.0)
        assert off == bare, f"default offset changed the command at alt_m={alt_m}"


def test_negative_offset_lowers_the_reference_by_exactly_that_much():
    for offset in (-0.20, -0.161, -0.204, -0.5):
        args = _args_from_cli(["--alt-ref-offset-m", str(offset)])
        assert args.alt_ref_offset_m == pytest.approx(offset, abs=0.0)
        assert M4.alt_ref_m(args) == pytest.approx(M4.ALT_REF_M + offset, abs=1e-12)
    # and a positive one raises it, so the sign convention is pinned both ways
    args = _args_from_cli(["--alt-ref-offset-m", "0.30"])
    assert M4.alt_ref_m(args) == pytest.approx(0.80, abs=1e-12)


def test_offset_reaches_the_altitude_command_MUTANT():
    """MUTANT-STYLE: this fails if the offset is parsed but IGNORED downstream.

    A hold that is 0.20 m lower must command a 0.20 m/s DESCENT at the height
    the unshifted hold called perfect (KP_ALT = 1.0 /s, well inside V_VERT_MAX),
    and must command ZERO at the new, lower reference. A build that dropped
    `alt_ref` on the floor returns 0.0 for the first case and -0.20 for the
    second, so both halves flip.
    """
    offset = -0.20
    args = _args_from_cli(["--alt-ref-offset-m", str(offset)])
    alt_ref = M4.alt_ref_m(args)
    assert abs(M4.KP_ALT * offset) < M4.V_VERT_MAX, "test point must not be clamped"

    # at the OLD reference the lowered hold now wants to come down
    v_down_at_old_ref = M4.acquire_command(
        False, None, M4.ALT_REF_M, 0.0, alt_ref=alt_ref)[2]
    assert v_down_at_old_ref == pytest.approx(-M4.KP_ALT * offset, abs=1e-12)
    assert v_down_at_old_ref > 0.0, "NED: +v_down is DOWN; the vehicle must descend"

    # at the NEW reference it is satisfied
    v_down_at_new_ref = M4.acquire_command(
        False, None, M4.ALT_REF_M + offset, 0.0, alt_ref=alt_ref)[2]
    assert v_down_at_new_ref == pytest.approx(0.0, abs=1e-12)

    # and the unshifted call at that same height wants to climb back up
    assert M4.acquire_command(
        False, None, M4.ALT_REF_M + offset, 0.0)[2] == pytest.approx(
            M4.KP_ALT * offset, abs=1e-12)


def test_no_altitude_hold_site_still_reads_the_bare_constant_MUTANT():
    """MUTANT-STYLE, structural: re-hardcoding ALT_REF_M at ANY hold site inside
    the two flight functions would silently ignore the offset on that phase
    only -- a per-phase partial revert that no single-phase behaviour test
    catches. AST, so a comment mentioning ALT_REF_M is not a finding."""
    import ast as _ast
    tree = _ast.parse(open(M4.__file__.replace(".pyc", ".py")).read())
    offenders = {}
    for node in _ast.walk(tree):
        if isinstance(node, (_ast.FunctionDef, _ast.AsyncFunctionDef)) and \
                node.name in ("run_acquire_and_engage", "run_bench"):
            hits = sorted({c.lineno for c in _ast.walk(node)
                           if isinstance(c, _ast.Name) and c.id == "ALT_REF_M"})
            if hits:
                offenders[node.name] = hits
    assert offenders == {}, (
        "ALT_REF_M is read directly inside a flight loop; it must come from "
        f"alt_ref = alt_ref_m(args) so --alt-ref-offset-m applies: {offenders}")


def test_offset_is_a_preflight_constant_not_a_ground_truth_read_MUTANT():
    """The offset describes the VEHICLE's own geometry. It must never be
    derived in flight from a gt_* value -- that would be the launch-aim
    loophole again, one datum over. AST: alt_ref_m's body reads only its
    `args` parameter and the module constant."""
    import ast as _ast
    tree = _ast.parse(open(M4.__file__.replace(".pyc", ".py")).read())
    fn = next(n for n in _ast.walk(tree)
              if isinstance(n, _ast.FunctionDef) and n.name == "alt_ref_m")
    names = {c.id for c in _ast.walk(fn) if isinstance(c, _ast.Name)}
    attrs = {c.attr for c in _ast.walk(fn) if isinstance(c, _ast.Attribute)}
    assert not any(n.startswith("gt_") for n in names | attrs), names | attrs
    assert names <= {"args", "off", "ALT_REF_M", "getattr", "float", "None"}, names


# ------------------------------------------- dash altitude gain (prereg §10) ---


def test_dash_alt_gain_default_is_stock():
    args = _args_from_cli([])
    assert args.dash_alt_kp is None and args.dash_alt_vmax is None
    assert M4.dash_alt_gain(args, M4.V_VERT_MAX) == (M4.KP_ALT, M4.V_VERT_MAX)
    # the loft path's raised clamp must pass through untouched when the gain is off
    assert M4.dash_alt_gain(args, 3.0) == (M4.KP_ALT, 3.0)


def test_dash_alt_gain_applies_and_vmax_needs_kp():
    args = _args_from_cli(["--dash-alt-kp", "4", "--dash-alt-vmax", "1.5"])
    assert M4.dash_alt_gain(args, M4.V_VERT_MAX) == (4.0, 1.5)
    args = _args_from_cli(["--dash-alt-vmax", "1.5"])
    assert M4.dash_alt_gain(args, M4.V_VERT_MAX) == (M4.KP_ALT, M4.V_VERT_MAX)


# --------------------------------- passage gate (issue #3 fallback, plan 5b) ---


def test_passage_gate_truth_table():
    g = M4.passage_gate_ok
    assert g(0.1, 8.0, None) is True          # OFF: always allows (byte-identical)
    assert g(None, None, None) is True
    assert g(6.3, 8.0, 0.8) is False          # 79% of the way: cannot have passed it
    assert g(6.4, 8.0, 0.8) is True
    assert g(None, 8.0, 0.8) is False         # FAIL-CLOSED on a missing own position
    assert g(6.4, None, 0.8) is False         # ... and on a missing plan
    assert g(6.4, 0.0, 0.8) is False


def test_passage_gate_is_wired_into_the_breakoff_and_default_off():
    args = _args_from_cli([])
    assert args.breakoff_min_flown_frac is None
    src = open(M4.__file__).read()
    assert src.count("and passage_ok\n                    ):") == 1, "gate not in the trigger"
    assert "coded_dash_plan_m = dash_ramp_distance(_vi, _lead_accel, _t_lead)" in src
    assert "coded_dash_start_ne = (state.pos_n, state.pos_e)" in src


# ------------------------------- predicted-LOS yaw (docs/pointing_prereg.md) ---


def test_predicted_los_yaw_geometry_and_fallbacks():
    f = M4.predicted_los_yaw_deg
    # target due NORTH of a vehicle that has not moved -> azimuth 0
    assert f((0.0, 10.0), (0.0, 0.0), 0.0, (0.0, 0.0), 54.0) == pytest.approx(0.0)
    # target due EAST -> +90 (compass, atan2(east, north))
    assert f((10.0, 0.0), (0.0, 0.0), 0.0, (0.0, 0.0), 54.0) == pytest.approx(90.0)
    # the target MOVES: 6.5 m east, starting 15 m north, 9 m/s southward, after 1 s
    assert f((6.5, 15.0), (0.0, -9.0), 1.0, (0.0, 0.0), 54.0) == pytest.approx(
        math.degrees(math.atan2(6.5, 6.0)))
    # own displacement is subtracted
    assert f((6.5, 15.0), (0.0, -9.0), 1.0, (6.5, 0.0), 54.0) == pytest.approx(0.0)
    # FALLBACKS: a missing input or a degenerate geometry returns the dash heading
    assert f((6.5, 15.0), (0.0, -9.0), None, (0.0, 0.0), 54.0) == 54.0
    assert f((6.5, 15.0), (0.0, -9.0), 1.0, None, 54.0) == 54.0
    assert f((0.1, 0.1), (0.0, 0.0), 0.0, (0.0, 0.0), 54.0) == 54.0


def test_predicted_los_yaw_is_default_off_and_wired():
    assert _args_from_cli([]).dash_yaw_to_predicted_los is False
    src = open(M4.__file__).read()
    assert "v_down, _dash_yaw_deg)" in src
    assert src.count("_dash_yaw_deg = coded_dash_heading_deg") == 1   # the OFF path


# ------------------------- pre-dash yaw alignment (pointing_prereg amendment) ---


def test_prealign_step_logic():
    f = M4.prealign_step
    assert f(10.0, 0, 0) == (False, 0, 1, False)
    ok = tot = 0
    for _ in range(M4.PREALIGN_HOLD_TICKS):
        done, ok, tot, timed_out = f(1.0, ok, tot)
    assert done and not timed_out and tot == M4.PREALIGN_HOLD_TICKS
    done, ok, tot, _ = f(None, 5, 3)
    assert not done and ok == 0, "a missing yaw reading must never count as aligned"
    done, ok, tot, timed_out = f(50.0, 0, M4.PREALIGN_MAX_TICKS - 1)
    assert done and timed_out, "must give up and SAY so, not hover forever"


def test_prealign_is_default_off_and_wired():
    assert _args_from_cli([]).dash_prealign_yaw is False
    src = open(M4.__file__).read()
    assert src.count('elif phase == "STANDBY":') == 1
    assert 'if phase == "CODED_DASH" and getattr(args, "dash_prealign_yaw", False):' in src


def test_passage_ceiling_truth_table_and_wiring():
    c = M4.passage_ceiling_hit
    assert c(100.0, 8.0, None) is False            # OFF
    assert c(10.3, 8.0, 1.3) is False
    assert c(10.4, 8.0, 1.3) is True
    assert c(None, 8.0, 1.3) is False              # a missing input never FORCES a breakoff
    assert c(10.4, None, 1.3) is False
    assert _args_from_cli([]).breakoff_force_flown_frac is None
    src = open(M4.__file__).read()
    assert src.count("if passage_ceiling_hit(_ceil_flown, coded_dash_plan_m,") == 1


def test_terminal_vclose_floor():
    f = M4.apply_vclose_floor
    assert f(5.5, None) == 5.5                 # OFF: the stock law, untouched
    assert f(5.5, 16.0) == 16.0 and f(9.0, 16.0) == 16.0
    assert f(20.0, 16.0) == 20.0               # a floor, never a cap
    assert _args_from_cli([]).terminal_vclose_min is None
    src = open(M4.__file__).read()
    assert src.count("v_close = apply_vclose_floor(v_close, args.terminal_vclose_min)") == 1
