#!/usr/bin/env python3
"""Guided, headless camera calibration: "hold the camera in front of the TV".

WHY THIS EXISTS (docs/bench_specs/tv_calibration.md). The builder keeps
skipping checkerboard calibration (skr-06: >=15 views, RMS <= 1.0 px). He has
a TV he can drive full-screen from `scripts/bench/calib_pattern.html`. This
script is the Pi-side half: point the camera at the TV, and it auto-KEEPS
frames for you (sharp + a pose that adds real coverage), tracks coverage on a
tiny web page you can watch on your phone, stops itself once the set is good,
and writes the intrinsics file `scripts/calibrate_camera.py` / `flight/
camera.py` already consume.

PHYSICS (read this before changing the board). A flat TV screen is ONE plane.
Warping the on-screen pattern does not create new views -- intrinsics need the
CAMERA to see the plane from different angles, so the pattern on screen stays
FIXED and bright, and the camera is the thing that moves. ChArUco (a
checkerboard with an ArUco marker in every other square) is used instead of a
plain checkerboard because a PARTIAL view -- the board clipped by the frame
edge -- still yields usable corners; a plain checkerboard needs the WHOLE
board in frame or it yields nothing. That matters here because the OV9281's
~118 deg HFoV lens sees the board across almost the whole frame width even at
a comfortable arm's length, and edge coverage is exactly what a wide lens's
distortion estimate depends on (see scripts/seeker/capture_calib_views.py's
own corner-zone comment).

THE BOARD, AND WHY THESE EXACT NUMBERS (do not change without re-reading this):
  - dictionary DICT_4X4_50, 7x5 squares, markerLength = 0.7 * squareLength,
    borderBits=1. 7x5 is ODD x ODD on purpose: OpenCV >=4.6.0 changed the
    ChArUco layout algorithm for EVEN row/column counts (cv2.aruco.CharucoBoard
    ::setLegacyPattern docs), which would make a board generated by one OpenCV
    version undetectable/mis-keyed by another. Verified empirically (this repo,
    2026-09-17): for 7x5 the legacy and non-legacy layouts are BIT-IDENTICAL,
    so the odd x odd choice sidesteps the whole version hazard instead of
    having to pin a flag both sides must agree on.
  - `board_cells_json()` below asks cv2 itself (not a hand-derived drawing)
    for the exact per-square bit pattern the real CharucoBoard object renders,
    and `scripts/bench/calib_pattern.html` embeds that JSON verbatim and draws
    it with <canvas> at the screen's native resolution. A photo of the TV
    showing that page is therefore bit-identical to what
    `cv2.aruco.CharucoBoard((7,5), squareLength, 0.7*squareLength, DICT_4X4_50)`
    expects to detect. tests/test_calib_live.py's contract test fails loudly if
    the HTML's embedded JSON and this function's output ever diverge.
  - The physical size only matters as a NUMBER, not a drawing choice (see
    scripts/seeker/capture_calib_views.py's docstring on why intrinsics are
    scale-invariant to object points): `calib_pattern.html` displays the
    square size in pixels and (given the TV's visible width in mm, or a ruled
    measurement) in millimetres; pass that number here as `--square-mm`.

COVERAGE MODEL (mirrors scripts/seeker/capture_calib_views.py's zones+buckets
pattern -- same idea, adapted to live auto-capture instead of manual grabs):
  - REGIONS: a 4 (columns) x 3 (rows) grid of where the board's centroid lands
    in the frame -- 12 cells.
  - TILT BINS: 3 bins (level / medium / steep) from the angle between the
    board's estimated pose normal and the camera's own optical axis (NOT the
    line of sight -- a board dead ahead of the lens reads ~0 deg regardless of
    where in the frame it sits, which is what "hold it level" / "tilt it"
    instructions mean to a human).
  - "Full coverage" = every one of the 12 regions has >=1 kept view AND every
    one of the 3 tilt bins has >=1 kept view (a UNION requirement on each axis
    separately, not the 36-cell cross product -- the stop condition also wants
    >=25 views, and requiring all 36 cross-product cells filled inside a
    ~2-minute session would be a contradictory target).
  - NOVELTY ("pose differs enough from those already kept"): a frame is kept
    only if its (region, tilt) bucket has fewer than `--max-per-bucket`
    (default 2) views already -- once a bucket is well sampled, a further
    view landing there is skipped so the ~2 minutes gets spent filling gaps,
    not repeating a pose already covered.
  - Pose is estimated by `cv2.solvePnP` against an APPROXIMATE camera matrix
    (118 deg HFoV assumed) -- good enough to bucket relative tilt, useless as
    a calibration input, and never written anywhere. The real intrinsics come
    only from the accumulated `cv2.calibrateCamera` / `cv2.fisheye.calibrate`
    solve once the session is done.

TWO SOLVES, ONE WRITTEN (the honesty-relevant decision here). Both a pinhole
(Brown-Conrady, `cv2.calibrateCamera`) and a fisheye (`cv2.fisheye.calibrate`)
model are fit and their RMS reprojection errors are BOTH reported -- a 118 deg
lens is a real candidate for the fisheye model reading meaningfully better.
But `flight/camera.py`'s `CameraModel` only implements the pinhole +
Brown-Conrady undistort math; it has no fisheye (equidistant) inverse. Writing
a fisheye K/D into that slot would silently corrupt every downstream range
computation the moment the seeker loaded it -- exactly the class of silent
failure CLAUDE.md's error-handling policy exists to prevent. So the file this
script writes (in `scripts/calibrate_camera.py`'s own JSON schema, so
`flight/camera.py` and `scripts/calibrate_camera.py --images` both accept it
unchanged) is ALWAYS the pinhole solve; the fisheye numbers are printed and
saved to a sibling `*_fisheye_diagnostic.json`, clearly labelled, for a human
to act on later if the pinhole model proves inadequate on real ranges.

FISHEYE NEEDS A FIXED POINT COUNT PER VIEW -- a real OpenCV constraint learned
the hard way while building this (cv2.fisheye.calibrate raises a raw
`arithm_op` size-mismatch error on ragged per-view point counts; pinhole's
`cv2.calibrateCamera` has no such restriction, which is exactly why the
partial edge views the spec wants still count there). So the fisheye solve
silently DROPS any kept view that does not see the board's full corner set,
and reports how many full views it used; if fewer than 4 remain it skips the
fisheye solve entirely rather than fail the whole session.

Usage:
    # the real bench session, on the Pi, camera pointed at the TV
    scripts/bench/calib_live.py --square-mm 42.7 --out camera_intrinsics_real.json
    # watch it from a phone on the same network: http://<pi-ip>:8000

    # dev / no camera: replay a directory of stills instead of picamera2
    scripts/bench/calib_live.py --square-mm 42.7 --source dir=/path/to/frames --auto 40

    # print the board's exact cell layout (for calib_pattern.html) -- no camera
    scripts/bench/calib_live.py --emit-board-json

    # offline self-check, no camera, no display, exits 0/1
    scripts/bench/calib_live.py --self-test

Requires cv2 (with cv2.aruco; falls back to a plain checkerboard if the local
OpenCV build lacks it) + numpy. On the Pi, run under whatever venv carries
picamera2 (the camera backend is imported lazily, same convention as
scripts/seeker/pi_capture.py).
"""
from __future__ import annotations

import argparse
import json
import math
import os
import sys
import threading
import time
from datetime import datetime, timezone
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

import numpy as np

try:
    import cv2
except ImportError:
    print("[calib-live] FAILED: opencv (cv2) not installed in this environment")
    sys.exit(2)

# --- imports from sibling/parent scripts (reuse, do not reimplement) -------
_HERE = os.path.dirname(os.path.abspath(__file__))          # .../scripts/bench
_SCRIPTS = os.path.dirname(_HERE)                            # .../scripts
_SEEKER = os.path.join(_SCRIPTS, "seeker")
_REPO = os.path.dirname(_SCRIPTS)
for _p in (_REPO, _SCRIPTS, _SEEKER):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from pi_capture import iter_dir, iter_picamera2, iter_v4l2  # noqa: E402
# The checkerboard corner finder + object-point builder -- reused verbatim for
# the fallback path so a view this tool accepts is one calibrate_camera.py
# would also accept (same convention as capture_calib_views.py).
from calibrate_camera import _find_corners, _object_points  # noqa: E402

LOG = "[calib-live]"

# --------------------------------------------------------------------------
# Board configuration -- the single source of truth for both this file and
# the JSON board_cells_json() emits for calib_pattern.html to draw.
# --------------------------------------------------------------------------
HAS_ARUCO = hasattr(cv2, "aruco")
ARUCO_DICT = "DICT_4X4_50"
SQUARES_X, SQUARES_Y = 7, 5   # ODD x ODD -- see module docstring
MARKER_RATIO = 0.7            # markerLength / squareLength
BORDER_BITS = 1
BITS_N = 4                    # DICT_4X4_* inner bit grid
CELL_BITS = BITS_N + 2 * BORDER_BITS   # 6: inner bits + the black border ring
GEN_CELL_PX = 240              # render resolution used only to sample bits

# Checkerboard fallback (only reached if this cv2 build has no cv2.aruco).
CB_COLS, CB_ROWS = 9, 6

# skr-06-style acceptance inputs, adapted to auto-capture coverage.
MIN_VIEWS = 25
REGION_COLS, REGION_ROWS = 4, 3
N_REGIONS = REGION_COLS * REGION_ROWS
REGION_COL_NAMES = ("left", "center-left", "center-right", "right")
REGION_ROW_NAMES = ("top", "middle", "bottom")
REGION_NAMES = tuple(f"{r}-{c}" for r in REGION_ROW_NAMES for c in REGION_COL_NAMES)
TILT_BINS = ("level", "medium", "steep")
TILT_THRESH_DEG = (15.0, 35.0)          # <15 level, 15-35 medium, >=35 steep
TILT_HINT = ("hold the board flat, facing the camera",
             "tilt the board about 20-30 degrees",
             "tilt the board sharply -- 40+ degrees, corner-on")
MAX_PER_JOINT_BUCKET = 2       # "pose differs enough" cap per (region, tilt)
MIN_POINTS_PER_VIEW = 8        # a view with fewer detected corners than this
                               # is dropped at DETECTION time (not just kept
                               # with a low weight): cv2.calibrateCamera's
                               # homography-based initial-intrinsics estimate
                               # can degenerate (a real OpenCV assertion,
                               # `initIntrinsicParams2D`) on a very sparse or
                               # near-collinear corner set -- e.g. a board
                               # seen edge-on so only one row of corners is
                               # visible. 8 of the board's 24 corners is
                               # enough to span a real 2-D area.
DEFAULT_MIN_SHARPNESS = 40.0   # Laplacian-variance floor on the board ROI;
                               # tune at the bench -- every rejection logs the
                               # measured value, so this is not a blind guess.
CALIB_EXPOSURE_US_DEFAULT = 2000   # midpoint of the spec's 1-4 ms test range;
                                   # if frames show flicker banding from the
                                   # TV backlight, retry at 1000/3000/4000.
ASSUMED_HFOV_DEG = 118.0       # OV9281 spec HFoV -- used ONLY to build a rough
                               # K for tilt bucketing, never written to output.


# --------------------------------------------------------------------------
# board_cells_json -- the exact per-cell bit layout, asked from cv2 itself.
# --------------------------------------------------------------------------

def board_cells_json(square_len=1.0):
    """The ADOPTED board's per-cell layout: black-square vs marker-square,
    and for marker cells the marker id + the exact (border-included) bit
    matrix cv2.aruco.CharucoBoard.generateImage() actually renders there.

    This is the SOURCE OF TRUTH `scripts/bench/calib_pattern.html` draws from
    (its inline JS embeds this dict verbatim) -- see the module docstring.
    Returns None if this cv2 build has no cv2.aruco (checkerboard fallback;
    calib_pattern.html has nothing to embed in that case, and the fallback
    board is a plain printable/drawable checkerboard instead)."""
    if not HAS_ARUCO:
        return None
    dictionary = cv2.aruco.getPredefinedDictionary(getattr(cv2.aruco, ARUCO_DICT))
    board = cv2.aruco.CharucoBoard((SQUARES_X, SQUARES_Y), square_len,
                                    square_len * MARKER_RATIO, dictionary)
    ids = board.getIds().flatten().tolist()
    cell_px = GEN_CELL_PX
    w, h = SQUARES_X * cell_px, SQUARES_Y * cell_px
    img = board.generateImage((w, h), marginSize=0, borderBits=BORDER_BITS)
    marker_total_px = MARKER_RATIO * cell_px
    bit_px = marker_total_px / CELL_BITS

    # Every candidate (marker id, rotation) bit pattern, sampled the same way
    # the board image is sampled below, so a match is a real pixel-level match.
    candidates = {}
    for mid in range(dictionary.bytesList.shape[0]):
        base = dictionary.generateImageMarker(mid, CELL_BITS * 40,
                                               borderBits=BORDER_BITS)
        step = base.shape[0] / CELL_BITS
        bits = np.zeros((CELL_BITS, CELL_BITS), dtype=np.uint8)
        for r in range(CELL_BITS):
            for c in range(CELL_BITS):
                y = int((r + 0.5) * step)
                x = int((c + 0.5) * step)
                bits[r, c] = 1 if base[y, x] > 127 else 0
        for rot in range(4):
            candidates[(mid, rot)] = np.rot90(bits, rot)

    cells = []
    for row in range(SQUARES_Y):
        for col in range(SQUARES_X):
            y0, x0 = row * cell_px, col * cell_px
            cell = img[y0:y0 + cell_px, x0:x0 + cell_px]
            if float((cell < 128).mean()) > 0.9:
                cells.append({"row": row, "col": col, "type": "black"})
                continue
            margin_px = (cell_px - marker_total_px) / 2.0
            my0, mx0 = y0 + margin_px, x0 + margin_px
            bits = np.zeros((CELL_BITS, CELL_BITS), dtype=np.uint8)
            for r in range(CELL_BITS):
                for c in range(CELL_BITS):
                    yy = int(my0 + (r + 0.5) * bit_px)
                    xx = int(mx0 + (c + 0.5) * bit_px)
                    bits[r, c] = 1 if img[yy, xx] > 127 else 0
            match = None
            for (mid, rot), cbits in candidates.items():
                if np.array_equal(bits, cbits):
                    match = (mid, rot)
                    break
            if match is None:
                raise RuntimeError(
                    f"board_cells_json: no dictionary match for cell "
                    f"row={row} col={col} -- the board geometry changed "
                    f"without regenerating calib_pattern.html's embedded JSON")
            mid, _rot = match
            cells.append({"row": row, "col": col, "type": "marker", "id": mid,
                          "bits": bits.tolist()})
    return {"dict": ARUCO_DICT, "squaresX": SQUARES_X, "squaresY": SQUARES_Y,
            "squareLength": square_len, "markerLength": square_len * MARKER_RATIO,
            "borderBits": BORDER_BITS, "bitsN": BITS_N, "cellBits": CELL_BITS,
            "ids": ids, "cells": cells}


# --------------------------------------------------------------------------
# Board adapters -- detection only; ChArUco primary, checkerboard fallback.
# --------------------------------------------------------------------------

class DetectedView:
    __slots__ = ("obj_pts", "img_pts", "draw_corners")

    def __init__(self, obj_pts, img_pts, draw_corners):
        self.obj_pts = obj_pts          # (N,3) float64, board frame, Z=0
        self.img_pts = img_pts          # (N,2) float64, pixel coords
        self.draw_corners = draw_corners  # whatever shape cv2 drew corners in


class CharucoBoardAdapter:
    kind = "charuco"

    def __init__(self, square_mm):
        dictionary = cv2.aruco.getPredefinedDictionary(getattr(cv2.aruco, ARUCO_DICT))
        square_m = square_mm / 1000.0
        marker_m = square_m * MARKER_RATIO
        self.board = cv2.aruco.CharucoBoard((SQUARES_X, SQUARES_Y), square_m,
                                             marker_m, dictionary)
        self.board.setLegacyPattern(False)  # explicit; see module docstring
        det_params = cv2.aruco.DetectorParameters()
        det_params.cornerRefinementMethod = cv2.aruco.CORNER_REFINE_SUBPIX
        charuco_params = cv2.aruco.CharucoParameters()
        self.detector = cv2.aruco.CharucoDetector(self.board, charuco_params,
                                                   det_params)
        self.full_n_points = len(self.board.getChessboardCorners())

    def detect(self, gray):
        corners, ids, _mc, _mi = self.detector.detectBoard(gray)
        if corners is None or ids is None or len(corners) < MIN_POINTS_PER_VIEW:
            return None
        obj_pts, img_pts = self.board.matchImagePoints(corners, ids)
        if obj_pts is None or len(obj_pts) < MIN_POINTS_PER_VIEW:
            return None
        return DetectedView(obj_pts.reshape(-1, 3).astype(np.float64),
                            img_pts.reshape(-1, 2).astype(np.float64),
                            draw_corners=corners)


class CheckerboardAdapter:
    kind = "checkerboard"

    def __init__(self, square_mm):
        self.cols, self.rows = CB_COLS, CB_ROWS
        square_m = square_mm / 1000.0
        self.objp = _object_points(self.cols, self.rows, square_m).astype(np.float64)
        self.full_n_points = self.cols * self.rows

    def detect(self, gray):
        corners = _find_corners(gray, self.cols, self.rows)
        if corners is None:
            return None
        img_pts = corners.reshape(-1, 2).astype(np.float64)
        return DetectedView(self.objp.copy(), img_pts, draw_corners=corners)


def make_adapter(square_mm):
    if HAS_ARUCO:
        return CharucoBoardAdapter(square_mm)
    print(f"{LOG} WARNING: this cv2 build has no cv2.aruco -- falling back to "
          f"a plain {CB_COLS}x{CB_ROWS} checkerboard. Partial/edge views will "
          f"NOT count (the whole board must be in frame), so coverage will "
          f"take longer to fill.")
    return CheckerboardAdapter(square_mm)


# --------------------------------------------------------------------------
# Region / tilt classification
# --------------------------------------------------------------------------

def classify_region(u, v, w, h):
    col = min(REGION_COLS - 1, max(0, int(u * REGION_COLS / w))) if w > 0 else REGION_COLS // 2
    row = min(REGION_ROWS - 1, max(0, int(v * REGION_ROWS / h))) if h > 0 else REGION_ROWS // 2
    return row * REGION_COLS + col


def classify_tilt(tilt_deg):
    if tilt_deg < TILT_THRESH_DEG[0]:
        return 0
    if tilt_deg < TILT_THRESH_DEG[1]:
        return 1
    return 2


def approx_k_guess(w, h, hfov_deg=ASSUMED_HFOV_DEG):
    """A rough camera matrix used ONLY to bucket relative pose for the
    coverage map -- never written to any output. See module docstring."""
    fx = (w / 2.0) / math.tan(math.radians(hfov_deg) / 2.0)
    return np.array([[fx, 0.0, w / 2.0], [0.0, fx, h / 2.0], [0.0, 0.0, 1.0]])


def estimate_tilt_deg(obj_pts, img_pts, k_guess):
    """Angle (deg) between the board's pose normal and the camera's OPTICAL
    AXIS (not the line of sight -- see module docstring). None if solvePnP
    fails to converge (never a fabricated 0.0 -- error policy)."""
    ok, rvec, _tvec = cv2.solvePnP(obj_pts.reshape(-1, 1, 3),
                                   img_pts.reshape(-1, 1, 2), k_guess, None)
    if not ok:
        return None
    R, _ = cv2.Rodrigues(rvec)
    c = min(1.0, max(-1.0, abs(float(R[2, 2]))))
    return math.degrees(math.acos(c))


def corners_bbox(draw_corners, w, h, margin=20):
    pts = np.asarray(draw_corners, dtype=float).reshape(-1, 2)
    x0, y0 = float(pts[:, 0].min()), float(pts[:, 1].min())
    x1, y1 = float(pts[:, 0].max()), float(pts[:, 1].max())
    return (max(0, int(x0 - margin)), max(0, int(y0 - margin)),
            min(w, int(x1 + margin)), min(h, int(y1 + margin)))


def sharpness_score(gray, bbox=None):
    if bbox is not None:
        x0, y0, x1, y1 = bbox
        if x1 <= x0 or y1 <= y0:
            return 0.0
        roi = gray[y0:y1, x0:x1]
    else:
        roi = gray
    if roi.size == 0:
        return 0.0
    return float(cv2.Laplacian(roi, cv2.CV_64F).var())


# --------------------------------------------------------------------------
# Coverage bookkeeping + keep decision
# --------------------------------------------------------------------------

class Coverage:
    def __init__(self):
        self.region_counts = [0] * N_REGIONS
        self.tilt_counts = [0] * len(TILT_BINS)
        self.bucket_counts = {}
        self.saved = 0
        self.rejected_no_board = 0
        self.rejected_blur = 0
        self.rejected_redundant = 0
        self.views = []

    def add(self, region, tilt, view):
        self.region_counts[region] += 1
        self.tilt_counts[tilt] += 1
        self.bucket_counts[(region, tilt)] = self.bucket_counts.get((region, tilt), 0) + 1
        self.saved += 1
        self.views.append(view)

    @property
    def regions_filled(self):
        return sum(1 for c in self.region_counts if c > 0)

    @property
    def tilts_filled(self):
        return sum(1 for c in self.tilt_counts if c > 0)

    def empty_regions(self):
        return [i for i, c in enumerate(self.region_counts) if c == 0]

    def empty_tilts(self):
        return [i for i, c in enumerate(self.tilt_counts) if c == 0]

    def is_ready(self, min_views=MIN_VIEWS):
        return (self.saved >= min_views and not self.empty_regions()
                and not self.empty_tilts())


def consider_frame(gray, adapter, cov, k_guess, min_sharpness=DEFAULT_MIN_SHARPNESS,
                    max_per_bucket=MAX_PER_JOINT_BUCKET):
    """Detection + quality/novelty gate on one frame. Never raises on a bad
    frame (fail-soft in a live loop, same convention as
    capture_calib_views.handle_frame). Returns a result dict describing what
    happened -- used both to drive the coverage map and to annotate the live
    view."""
    h, w = gray.shape[:2]
    det = adapter.detect(gray)
    if det is None:
        cov.rejected_no_board += 1
        return {"found": False, "kept": False, "reason": "no board detected"}
    tilt_deg = estimate_tilt_deg(det.obj_pts, det.img_pts, k_guess)
    if tilt_deg is None:
        cov.rejected_no_board += 1
        return {"found": True, "kept": False, "reason": "pose failed"}
    cx, cy = float(det.img_pts[:, 0].mean()), float(det.img_pts[:, 1].mean())
    region = classify_region(cx, cy, w, h)
    tilt = classify_tilt(tilt_deg)
    bbox = corners_bbox(det.draw_corners, w, h)
    sharp = sharpness_score(gray, bbox)
    base = {"found": True, "region": region, "tilt": tilt, "tilt_deg": tilt_deg,
            "sharpness": sharp, "bbox": bbox, "n_pts": len(det.obj_pts)}
    if sharp < min_sharpness:
        cov.rejected_blur += 1
        return {**base, "kept": False,
                "reason": f"too blurry ({sharp:.0f} < {min_sharpness:.0f})"}
    if cov.bucket_counts.get((region, tilt), 0) >= max_per_bucket:
        cov.rejected_redundant += 1
        return {**base, "kept": False,
                "reason": "pose too similar to views already kept"}
    cov.add(region, tilt, {"obj_pts": det.obj_pts, "img_pts": det.img_pts,
                           "n_pts": len(det.obj_pts)})
    return {**base, "kept": True, "reason": "kept"}


def instruction_for(cov, min_views=MIN_VIEWS):
    """One plain-English instruction -- the whole point of the live web page.
    Deterministic order (first empty region, then first empty tilt bin) so it
    does not thrash between two equally-empty cells frame to frame."""
    if cov.is_ready(min_views):
        return "Done -- enough views with full coverage. Solving..."
    empty_r = cov.empty_regions()
    if empty_r:
        return f"put the board in the {REGION_NAMES[empty_r[0]]} of the frame"
    empty_t = cov.empty_tilts()
    if empty_t:
        return TILT_HINT[empty_t[0]]
    remaining = max(0, min_views - cov.saved)
    if remaining > 0:
        return f"keep moving the board around -- {remaining} more view(s) needed"
    return "Done -- enough views with full coverage. Solving..."


# --------------------------------------------------------------------------
# Solvers
# --------------------------------------------------------------------------

def solve_pinhole(obj_list, img_list, image_size):
    """cv2.calibrateCamera can raise a raw `initIntrinsicParams2D` assertion
    if any ONE view's points are too sparse/near-collinear for its internal
    homography-based initial guess -- consider_frame's MIN_POINTS_PER_VIEW
    gate makes this rare, not impossible (a bench session could still bank a
    borderline view). Rather than let one bad view crash the whole ~2-minute
    session at the very end, retry once dropping the sparsest views."""
    def _solve(objs, imgs):
        objp = [np.asarray(o, dtype=np.float32).reshape(-1, 1, 3) for o in objs]
        imgp = [np.asarray(i, dtype=np.float32).reshape(-1, 1, 2) for i in imgs]
        return cv2.calibrateCamera(objp, imgp, image_size, None, None)

    try:
        rms, K, dist, _rv, _tv = _solve(obj_list, img_list)
        return rms, K, dist, len(obj_list)
    except cv2.error as e:
        n_before = len(obj_list)
        keep = [i for i, o in enumerate(obj_list) if len(o) >= MIN_POINTS_PER_VIEW + 4]
        if len(keep) < 5 or len(keep) == n_before:
            raise
        print(f"{LOG} WARNING: cv2.calibrateCamera failed on the full "
              f"{n_before}-view set ({e}); retrying with the "
              f"{len(keep)} least-sparse views only")
        objs2 = [obj_list[i] for i in keep]
        imgs2 = [img_list[i] for i in keep]
        rms, K, dist, _rv, _tv = _solve(objs2, imgs2)
        return rms, K, dist, len(keep)


def _fisheye_flag(name):
    """cv2 exposes the fisheye CALIB_* flags in DIFFERENT places depending on
    the OpenCV build: under cv2.fisheye on the Pi's system OpenCV (4.10.0,
    verified 2026-09-17) and at the top-level cv2.* on this repo's dev .venv
    (5.0.0). Try both rather than assume one -- an AttributeError here would
    otherwise crash the fisheye solve on whichever machine wasn't tested."""
    if hasattr(cv2.fisheye, name):
        return getattr(cv2.fisheye, name)
    return getattr(cv2, name)


def solve_fisheye(obj_list, img_list, image_size, full_n_points):
    """Fit the fisheye (equidistant) model. cv2.fisheye.calibrate requires
    EVERY view to carry the SAME number of points (a real OpenCV binding
    constraint -- see module docstring), so this uses only the kept views
    that saw the board's full corner set; returns None if fewer than 4
    qualify rather than raise."""
    idx = [i for i, o in enumerate(obj_list) if len(o) == full_n_points]
    if len(idx) < 4:
        return None
    objp = np.array([np.asarray(obj_list[i], dtype=np.float64).reshape(1, -1, 3)
                     for i in idx])
    imgp = np.array([np.asarray(img_list[i], dtype=np.float64).reshape(1, -1, 2)
                     for i in idx])
    flags = _fisheye_flag("CALIB_RECOMPUTE_EXTRINSIC") | _fisheye_flag("CALIB_FIX_SKEW")
    try:
        rms, K, D, _rv, _tv = cv2.fisheye.calibrate(objp, imgp, image_size,
                                                    None, None, flags=flags)
    except cv2.error as e:
        print(f"{LOG} fisheye solve FAILED on {len(idx)} full-board views: {e}")
        return None
    return rms, K, D, len(idx)


def write_intrinsics_json(path, K, dist, image_size, n_views, rms, source):
    """Same schema as scripts/calibrate_camera.py's _write_json (kept as a
    separate writer here, not a shared function, so this file never has to
    edit that one -- tests/test_calib_live.py's schema-drift check compares
    the two key sets so they cannot silently diverge)."""
    w, h = image_size
    out = {
        "source": source,
        "resolution": {"width": int(w), "height": int(h)},
        "fx": float(K[0, 0]), "fy": float(K[1, 1]),
        "cx": float(K[0, 2]), "cy": float(K[1, 2]),
        "dist_coeffs": [float(x) for x in np.asarray(dist).flatten()],
        "rms_reproj_error_px": float(rms),
        "n_views": int(n_views),
        "recorded_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    }
    with open(path, "w") as f:
        json.dump(out, f, indent=2)
    return out


# --------------------------------------------------------------------------
# Tiny web UI -- one status page, polled from a phone
# --------------------------------------------------------------------------

INDEX_HTML = """<!doctype html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>camera calibration</title>
<style>
body{font-family:sans-serif;background:#111;color:#eee;margin:0;padding:12px}
h1{font-size:1.1em;margin:0 0 8px}
#instr{font-size:1.4em;font-weight:bold;padding:10px;background:#223;border-radius:8px;margin-bottom:10px}
#live{width:100%;max-width:640px;border:1px solid #444;border-radius:4px}
table{border-collapse:collapse;margin-top:8px}
td{border:1px solid #444;width:34px;height:28px;text-align:center;font-size:0.8em}
.filled{background:#274}
.empty{background:#422}
#tiltrow td{width:80px}
#stats{margin-top:8px;font-size:0.9em;color:#aaa}
</style></head><body>
<h1>Camera calibration -- hold the camera in front of the TV</h1>
<div id="instr">connecting...</div>
<img id="live" src="/frame.jpg">
<div id="stats"></div>
<h3>region coverage (12 cells)</h3>
<table id="regiontab"></table>
<h3>tilt coverage</h3>
<table id="tilttab"><tr id="tiltrow"></tr></table>
<script>
function refresh(){
  fetch('/status.json').then(r=>r.json()).then(function(s){
    document.getElementById('instr').textContent = s.instruction;
    document.getElementById('stats').textContent =
      'views: ' + s.n_kept + ' / ' + s.min_views +
      '   regions: ' + s.regions_filled + '/' + s.n_regions +
      '   rejected (blur/no-board/redundant): ' +
      s.rejected_blur + '/' + s.rejected_no_board + '/' + s.rejected_redundant +
      (s.done ? ('   DONE (pinhole rms=' + (s.rms_pinhole||'?') + 'px)') : '');
    var rt = document.getElementById('regiontab');
    rt.innerHTML = '';
    for (var row=0; row<3; row++){
      var tr = document.createElement('tr');
      for (var col=0; col<4; col++){
        var td = document.createElement('td');
        var n = s.region_counts[row*4+col];
        td.className = n>0 ? 'filled' : 'empty';
        td.textContent = n;
        tr.appendChild(td);
      }
      rt.appendChild(tr);
    }
    var tt = document.getElementById('tiltrow');
    tt.innerHTML = '';
    for (var i=0;i<s.tilt_names.length;i++){
      var td = document.createElement('td');
      var n = s.tilt_counts[i];
      td.className = n>0 ? 'filled' : 'empty';
      td.textContent = s.tilt_names[i] + ': ' + n;
      tt.appendChild(td);
    }
  }).catch(function(){document.getElementById('instr').textContent='(no connection)';});
  document.getElementById('live').src = '/frame.jpg?t=' + Date.now();
}
setInterval(refresh, 700);
refresh();
</script></body></html>"""


class SharedState:
    def __init__(self):
        self._lock = threading.Lock()
        self._frame_jpeg = b""
        self._status = {"ready": False, "done": False, "n_kept": 0,
                         "min_views": MIN_VIEWS, "instruction": "starting...",
                         "region_counts": [0] * N_REGIONS, "n_regions": N_REGIONS,
                         "regions_filled": 0, "tilt_counts": [0] * len(TILT_BINS),
                         "tilt_names": list(TILT_BINS), "rejected_no_board": 0,
                         "rejected_blur": 0, "rejected_redundant": 0}

    def set_frame(self, jpeg_bytes):
        with self._lock:
            self._frame_jpeg = jpeg_bytes

    def get_frame(self):
        with self._lock:
            return self._frame_jpeg

    def set_status(self, d):
        with self._lock:
            self._status = dict(d)

    def get_status(self):
        with self._lock:
            return dict(self._status)


class Handler(BaseHTTPRequestHandler):
    state = None  # injected by start_server

    def log_message(self, *_a, **_k):
        pass  # quiet -- this runs on the bench, not for log-watching

    def _send(self, code, ctype, body):
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        try:
            if self.path.startswith("/status.json"):
                self._send(200, "application/json",
                          json.dumps(self.state.get_status()).encode())
            elif self.path.startswith("/frame.jpg"):
                body = self.state.get_frame()
                self._send(200 if body else 503, "image/jpeg", body)
            elif self.path == "/" or self.path.startswith("/index"):
                self._send(200, "text/html", INDEX_HTML.encode())
            else:
                self._send(404, "text/plain", b"not found")
        except (BrokenPipeError, ConnectionResetError):
            pass  # a phone browser navigating away mid-response is normal


def start_server(state, host, port):
    Handler.state = state
    server = ThreadingHTTPServer((host, port), Handler)
    t = threading.Thread(target=server.serve_forever, daemon=True)
    t.start()
    return server, t


def _annotate(gray, result):
    img = cv2.cvtColor(gray, cv2.COLOR_GRAY2BGR)
    if result.get("found") and "bbox" in result:
        x0, y0, x1, y1 = result["bbox"]
        color = (0, 255, 0) if result.get("kept") else (0, 165, 255)
        cv2.rectangle(img, (x0, y0), (x1, y1), color, 2)
    label = "KEPT" if result.get("kept") else ("FOUND" if result.get("found") else "NO BOARD")
    cv2.putText(img, label, (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 1.0,
               (255, 255, 255), 2)
    return img


# --------------------------------------------------------------------------
# Main capture loop
# --------------------------------------------------------------------------

def _open_source(args):
    src = args.source
    if src.startswith("dir="):
        return iter_dir(cv2, src[len("dir="):], args.auto or 0, 30.0)
    if src.startswith("v4l2"):
        device = src.split("=", 1)[1] if "=" in src else 0
        return iter_v4l2(cv2, device, args.width, args.height, args.exposure_us,
                         args.gain, 0, None)
    if src == "picamera2":
        return iter_picamera2(cv2, args.width, args.height, args.exposure_us,
                              args.gain, 0, None)
    raise SystemExit(f"{LOG} unknown --source {src!r} "
                     f"(use picamera2, dir=PATH, or v4l2[=DEVICE])")


def run(args):
    adapter = make_adapter(args.square_mm)
    if adapter.kind == "charuco":
        print(f"{LOG} board: ChArUco {SQUARES_X}x{SQUARES_Y} squares, "
              f"square={args.square_mm:.2f} mm ({ARUCO_DICT})")
    else:
        print(f"{LOG} board: checkerboard {CB_COLS}x{CB_ROWS} inner corners, "
              f"square={args.square_mm:.2f} mm")
    cov = Coverage()
    state = SharedState()
    _server, _t = start_server(state, args.host, args.port)
    print(f"{LOG} serving http://{args.host}:{args.port} -- watch it on your phone")
    print(f"{LOG} goal: >= {args.min_views} views, all {N_REGIONS} frame regions, "
          f"all {len(TILT_BINS)} tilt bins")

    k_guess = approx_k_guess(args.width, args.height)
    gen = _open_source(args)
    image_size = None
    n_seen = 0
    try:
        for fr in gen:
            n_seen += 1
            gray = fr.gray
            if gray is None:
                continue
            if image_size is None:
                image_size = (gray.shape[1], gray.shape[0])
            result = consider_frame(gray, adapter, cov, k_guess,
                                     args.min_sharpness, args.max_per_bucket)
            status = {
                "n_kept": cov.saved, "min_views": args.min_views,
                "regions_filled": cov.regions_filled, "n_regions": N_REGIONS,
                "region_counts": list(cov.region_counts),
                "region_names": list(REGION_NAMES),
                "tilt_counts": list(cov.tilt_counts), "tilt_names": list(TILT_BINS),
                "rejected_no_board": cov.rejected_no_board,
                "rejected_blur": cov.rejected_blur,
                "rejected_redundant": cov.rejected_redundant,
                "instruction": instruction_for(cov, args.min_views),
                "ready": cov.is_ready(args.min_views), "done": False,
            }
            state.set_status(status)
            ok_enc, buf = cv2.imencode(".jpg", _annotate(gray, result),
                                       [cv2.IMWRITE_JPEG_QUALITY, 70])
            if ok_enc:
                state.set_frame(buf.tobytes())
            if result.get("kept"):
                print(f"{LOG} KEPT {cov.saved}/{args.min_views}  "
                      f"region={REGION_NAMES[result['region']]} "
                      f"tilt={TILT_BINS[result['tilt']]} "
                      f"({result['tilt_deg']:.0f} deg)  sharp={result['sharpness']:.0f}  "
                      f"regions={cov.regions_filled}/{N_REGIONS} "
                      f"tilts={cov.tilts_filled}/{len(TILT_BINS)}")
            if cov.is_ready(args.min_views):
                break
            if args.auto and n_seen >= args.auto:
                break
    except KeyboardInterrupt:
        print(f"\n{LOG} interrupted -- reporting what was captured so far.")
    finally:
        try:
            gen.close()
        except Exception:
            pass

    ready = cov.is_ready(args.min_views)
    print(f"{LOG} ---------------- session summary ----------------")
    print(f"{LOG} kept {cov.saved} views (need >= {args.min_views}); "
          f"regions {cov.regions_filled}/{N_REGIONS}; "
          f"tilts {cov.tilts_filled}/{len(TILT_BINS)}")
    if cov.empty_regions():
        print(f"{LOG} EMPTY regions: "
              + ", ".join(REGION_NAMES[i] for i in cov.empty_regions()))
    if cov.empty_tilts():
        print(f"{LOG} EMPTY tilt bins: "
              + ", ".join(TILT_BINS[i] for i in cov.empty_tilts()))
    if not ready or image_size is None:
        print(f"{LOG} VERDICT: NOT READY -- stopped early. Re-run to keep "
              f"filling gaps (this session's views are not saved to disk and "
              f"are not reused across runs).")
        state.set_status({**state.get_status(), "done": True, "ready": False})
        return 1

    obj_list = [v["obj_pts"] for v in cov.views]
    img_list = [v["img_pts"] for v in cov.views]
    rms_p, K_p, dist_p, n_used_p = solve_pinhole(obj_list, img_list, image_size)
    print(f"{LOG} PINHOLE  fx={K_p[0, 0]:.2f} fy={K_p[1, 1]:.2f} "
          f"cx={K_p[0, 2]:.2f} cy={K_p[1, 2]:.2f}  rms={rms_p:.3f}px "
          f"over {n_used_p} views")

    rms_f = None
    fe = solve_fisheye(obj_list, img_list, image_size, adapter.full_n_points)
    if fe is None:
        print(f"{LOG} FISHEYE  skipped (fewer than 4 full-board views -- every "
              f"kept view must see all {adapter.full_n_points} board points; "
              f"partial edge views, which the pinhole solve above DOES use, "
              f"don't qualify)")
    else:
        rms_f, K_f, D_f, n_full = fe
        print(f"{LOG} FISHEYE  fx={K_f[0, 0]:.2f} fy={K_f[1, 1]:.2f} "
              f"cx={K_f[0, 2]:.2f} cy={K_f[1, 2]:.2f}  rms={rms_f:.3f}px "
              f"over {n_full} full-board views")
        if rms_f < rms_p * 0.67:
            print(f"{LOG} NOTE: fisheye RMS is notably lower than pinhole -- "
                  f"this 118 deg lens may be better modeled as fisheye. "
                  f"flight/camera.py's CameraModel only supports pinhole + "
                  f"Brown-Conrady today, so the PINHOLE result is what gets "
                  f"written; treat the fisheye numbers as diagnostic.")
        fpath = os.path.splitext(args.out)[0] + "_fisheye_diagnostic.json"
        with open(fpath, "w") as f:
            json.dump({
                "note": "DIAGNOSTIC ONLY -- flight/camera.py cannot consume "
                        "the fisheye distortion model; this is not read by "
                        "any flight code.",
                "fx": float(K_f[0, 0]), "fy": float(K_f[1, 1]),
                "cx": float(K_f[0, 2]), "cy": float(K_f[1, 2]),
                "dist_coeffs_k1234": [float(x) for x in np.asarray(D_f).flatten()],
                "rms_reproj_error_px": float(rms_f), "n_views": n_full,
            }, f, indent=2)
        print(f"{LOG} wrote {fpath} (diagnostic, not consumed by flight code)")

    out = write_intrinsics_json(args.out, K_p, dist_p, image_size, n_used_p,
                                rms_p, source=f"{adapter.kind}_tv")
    print(f"{LOG} wrote {args.out}")
    if out["rms_reproj_error_px"] > 1.0:
        print(f"{LOG} WARNING: pinhole RMS > 1.0px -- marginal; recapture "
              f"with more spread before trusting ranges.")
    state.set_status({**state.get_status(), "done": True, "ready": True,
                      "rms_pinhole": rms_p, "rms_fisheye": rms_f})
    time.sleep(2)  # let the phone page show the final status before exit
    return 0


# --------------------------------------------------------------------------
# Offline self-test -- no camera, no display, exits 0/1
# --------------------------------------------------------------------------

def self_test():
    import shutil
    import tempfile

    checks = []

    def ck(name, ok, detail=""):
        checks.append((name, bool(ok), detail))
        print(f"{LOG}   [{'PASS' if ok else 'FAIL'}] {name}"
              + (f" -- {detail}" if detail else ""))

    if not HAS_ARUCO:
        print(f"{LOG} cv2.aruco not available -- self-test covers the "
              f"checkerboard fallback path only.")

    # ---- board_cells_json is internally consistent (ids sequential, cell count)
    if HAS_ARUCO:
        spec = board_cells_json(1.0)
        n_marker = sum(1 for c in spec["cells"] if c["type"] == "marker")
        ids_in_order = [c["id"] for c in spec["cells"] if c["type"] == "marker"]
        ck("board_cells_json: all 35 cells classified",
           len(spec["cells"]) == SQUARES_X * SQUARES_Y)
        ck("board_cells_json: marker ids are sequential 0..N-1 in reading order",
           ids_in_order == list(range(n_marker)), f"{ids_in_order}")

        # ---- tilt/region math on synthetic (analytic) points
        board = cv2.aruco.CharucoBoard((SQUARES_X, SQUARES_Y), 1.0,
                                       MARKER_RATIO, cv2.aruco.getPredefinedDictionary(
                                           getattr(cv2.aruco, ARUCO_DICT)))
        objp = board.getChessboardCorners()
        K = approx_k_guess(1280, 800)
        img_flat, _ = cv2.projectPoints(objp, np.zeros(3), np.array([0.0, 0.0, 5.0]), K, None)
        tilt_flat = estimate_tilt_deg(objp, img_flat.reshape(-1, 2), K)
        ck("estimate_tilt_deg: fronto-parallel board reads LEVEL",
           tilt_flat is not None and classify_tilt(tilt_flat) == 0,
           f"tilt={tilt_flat}")
        rvec_steep = np.array([math.radians(50.0), 0.0, 0.0])
        img_steep, _ = cv2.projectPoints(objp, rvec_steep, np.array([0.0, 0.0, 5.0]), K, None)
        tilt_steep = estimate_tilt_deg(objp, img_steep.reshape(-1, 2), K)
        ck("estimate_tilt_deg: a 50 deg rotated board reads STEEP",
           tilt_steep is not None and classify_tilt(tilt_steep) == 2,
           f"tilt={tilt_steep}")

    ck("classify_region: a point in the middle-row, third-column cell lands there",
       classify_region(800, 400, 1280, 800) == 1 * REGION_COLS + 2)
    ck("classify_region: top-left pixel maps to region 0",
       classify_region(0, 0, 1280, 800) == 0)

    # ---- solver self-checks (synthetic projected points, known K_true)
    ok_pin = _solver_self_check_pinhole()
    ck("solve_pinhole recovers fx within 1% on synthetic views", ok_pin)
    ok_fish = _solver_self_check_fisheye()
    ck("solve_fisheye recovers fx within 1% on synthetic views", ok_fish)

    # ---- writer + downstream consumer
    tmp = tempfile.mkdtemp(prefix="calib_live_selftest_")
    try:
        K = np.array([[400.0, 0, 640.0], [0, 400.0, 400.0], [0, 0, 1.0]])
        dist = np.array([-0.2, 0.05, 0.001, -0.001, 0.0])
        out_path = os.path.join(tmp, "intrinsics.json")
        out = write_intrinsics_json(out_path, K, dist, (1280, 800), 25, 0.42,
                                    source="charuco_tv")
        ck("write_intrinsics_json wrote a readable file", os.path.exists(out_path))
        sys.path.insert(0, _REPO)
        from flight.camera import CameraModel
        m = CameraModel.from_dict(out)
        ck("flight.camera.CameraModel loads the written file",
           abs(m.fx - 400.0) < 1e-6 and m.has_distortion and m.width == 1280)
        from calibrate_camera import _write_json
        ref_path = os.path.join(tmp, "ref.json")
        _write_json(ref_path, K, dist, (1280, 800), 25, 0.42)
        with open(ref_path) as f:
            ref_keys = set(json.load(f).keys())
        ck("written schema matches calibrate_camera.py's own key set",
           set(out.keys()) == ref_keys, f"{set(out.keys())} vs {ref_keys}")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    n_fail = sum(1 for _n, ok, _d in checks if not ok)
    print(f"{LOG} SELF-TEST {'PASS' if n_fail == 0 else 'FAIL'} "
          f"({len(checks) - n_fail}/{len(checks)} checks passed)")
    return 0 if n_fail == 0 else 1


def _solver_self_check_pinhole():
    K_true = np.array([[380.0, 0, 640.0], [0, 380.0, 400.0], [0, 0, 1.0]])
    dist_true = np.array([-0.28, 0.08, 0.001, -0.001, 0.0])
    rng = np.random.default_rng(3)
    board_pts = np.zeros((24, 3), np.float64)
    board_pts[:, :2] = np.mgrid[0:6, 0:4].T.reshape(-1, 2).astype(np.float64) * 0.04
    obj_list, img_list = [], []
    for _ in range(28):
        n = rng.integers(8, 24)
        idx = rng.choice(24, size=n, replace=False)
        op = board_pts[idx]
        rvec = rng.uniform(-0.5, 0.5, 3)
        tvec = np.array([rng.uniform(-0.15, 0.15), rng.uniform(-0.15, 0.15),
                         rng.uniform(0.4, 0.9)])
        ip, _ = cv2.projectPoints(op.reshape(-1, 1, 3), rvec, tvec, K_true, dist_true)
        obj_list.append(op)
        img_list.append(ip.reshape(-1, 2))
    rms, K, _dist, _n = solve_pinhole(obj_list, img_list, (1280, 800))
    return abs(K[0, 0] - K_true[0, 0]) / K_true[0, 0] < 0.01 and rms < 1.0


def _solver_self_check_fisheye():
    K_true = np.array([[380.0, 0, 640.0], [0, 380.0, 400.0], [0, 0, 1.0]])
    D_true = np.array([0.05, -0.01, 0.001, -0.0002])
    rng = np.random.default_rng(4)
    board_pts = np.zeros((24, 3), np.float64)
    board_pts[:, :2] = np.mgrid[0:6, 0:4].T.reshape(-1, 2).astype(np.float64) * 0.04
    obj_list, img_list = [], []
    tries = 0
    while len(obj_list) < 25 and tries < 200:
        tries += 1
        rvec = rng.uniform(-0.6, 0.6, 3)
        tvec = np.array([rng.uniform(-0.15, 0.15), rng.uniform(-0.15, 0.15),
                         rng.uniform(0.35, 0.9)])
        ip, _ = cv2.fisheye.projectPoints(board_pts.reshape(-1, 1, 3), rvec, tvec,
                                          K_true, D_true)
        pts = ip.reshape(-1, 2)
        if (pts[:, 0].min() < 0 or pts[:, 0].max() > 1280
                or pts[:, 1].min() < 0 or pts[:, 1].max() > 800):
            continue
        obj_list.append(board_pts)
        img_list.append(pts)
    fe = solve_fisheye(obj_list, img_list, (1280, 800), 24)
    if fe is None:
        return False
    rms, K, _D, _n = fe
    return abs(K[0, 0] - K_true[0, 0]) / K_true[0, 0] < 0.01 and rms < 1.0


# --------------------------------------------------------------------------

def main(argv=None):
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--square-mm", type=float,
                    help="square size in mm, read off scripts/bench/calib_pattern.html")
    ap.add_argument("--source", default="picamera2",
                    help="picamera2 (default) | dir=PATH | v4l2[=DEVICE]")
    ap.add_argument("--width", type=int, default=1280)
    ap.add_argument("--height", type=int, default=800)
    ap.add_argument("--exposure-us", type=int, default=CALIB_EXPOSURE_US_DEFAULT,
                    help=f"fixed exposure, microseconds (default "
                         f"{CALIB_EXPOSURE_US_DEFAULT}; spec test range is "
                         f"1000-4000 -- if frames flicker/band from the TV's "
                         f"backlight, retry with 1000/3000/4000)")
    ap.add_argument("--gain", type=float, default=4.0)
    ap.add_argument("--host", default="0.0.0.0")
    ap.add_argument("--port", type=int, default=8000)
    ap.add_argument("--out", default="camera_intrinsics_real.json")
    ap.add_argument("--min-views", type=int, default=MIN_VIEWS)
    ap.add_argument("--max-per-bucket", type=int, default=MAX_PER_JOINT_BUCKET)
    ap.add_argument("--min-sharpness", type=float, default=DEFAULT_MIN_SHARPNESS)
    ap.add_argument("--auto", type=int, default=0, metavar="N",
                    help="stop after N frames regardless of coverage "
                         "(testing / non-interactive dir replay; 0 = unbounded)")
    ap.add_argument("--emit-board-json", action="store_true",
                    help="print the ChArUco board's cell-layout JSON (for "
                         "embedding in calib_pattern.html) and exit; no camera")
    ap.add_argument("--self-test", action="store_true",
                    help="offline checks, no camera/display; exit 0/1")
    args = ap.parse_args(argv)

    if args.self_test:
        return self_test()
    if args.emit_board_json:
        spec = board_cells_json()
        if spec is None:
            print(f"{LOG} this cv2 build has no cv2.aruco -- nothing to emit "
                  f"(the fallback board is a plain checkerboard, drawn "
                  f"directly, not from a JSON table)")
            return 1
        print(json.dumps(spec))
        return 0
    if not args.square_mm:
        ap.error("--square-mm is required (read it off calib_pattern.html), "
                 "or use --self-test / --emit-board-json")
    return run(args)


if __name__ == "__main__":
    sys.exit(main())
